// ============================================
// JK RAFFLE ECOSYSTEM - Comprehensive Mock Data
// Generated for development & demo purposes
// All data is fictional but realistic for South Africa
// ============================================

import type {
  Branch,
  User,
  Product,
  Campaign,
  Ticket,
  Order,
  Payment,
  Notification,
  ActivityLog,
  SupportTicket,
  Event,
  DashboardStats,
  CampaignStatus,
  TicketStatus,
  OrderStatus,
  PaymentStatus,
  NotificationStatus,
  SupportTicketStatus,
  SupportTicketPriority,
  EventStatus,
  EventTypes,
  ProductCategory,
  UserRole,
  UserStatus,
} from '@/types';

// ============================================
// 1. BRANCHES (20 across South Africa)
// ============================================

export const mockBranches: Branch[] = [
  {
    id: 'branch-jhb-n',
    name: 'Johannesburg North',
    code: 'JHB-N',
    province: 'Gauteng',
    city: 'Johannesburg',
    address: '145 Sandton City Mall, Rivonia Rd, Sandton, 2196',
    phone: '+27 11 234 5001',
    email: 'sandton@jkraffle.co.za',
    managerId: 'user-david',
    status: 'active',
    memberCount: 342,
    revenue: 1450000,
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'branch-jhb-s',
    name: 'Johannesburg South',
    code: 'JHB-S',
    province: 'Gauteng',
    city: 'Johannesburg',
    address: '88 Gold Reef City, Northern Pkwy, Ormonde, 2001',
    phone: '+27 11 234 5002',
    email: 'jhb-south@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 218,
    revenue: 890000,
    createdAt: '2024-02-01T08:00:00Z',
  },
  {
    id: 'branch-jhb-e',
    name: 'Johannesburg East',
    code: 'JHB-E',
    province: 'Gauteng',
    city: 'Johannesburg',
    address: '42 Eastgate Shopping Centre, Bradford Rd, Bedfordview, 2007',
    phone: '+27 11 234 5003',
    email: 'bedfordview@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 156,
    revenue: 620000,
    createdAt: '2024-03-10T08:00:00Z',
  },
  {
    id: 'branch-cpt-c',
    name: 'Cape Town Central',
    code: 'CPT-C',
    province: 'Western Cape',
    city: 'Cape Town',
    address: '200 V&A Waterfront, Dock Rd, V&A Waterfront, 8002',
    phone: '+27 21 234 6001',
    email: 'waterfront@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 410,
    revenue: 1720000,
    createdAt: '2024-01-20T08:00:00Z',
  },
  {
    id: 'branch-cpt-s',
    name: 'Cape Town Southern Suburbs',
    code: 'CPT-S',
    province: 'Western Cape',
    city: 'Cape Town',
    address: '56 Cavendish Square, Claremont, 7708',
    phone: '+27 21 234 6002',
    email: 'claremont@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 189,
    revenue: 780000,
    createdAt: '2024-04-05T08:00:00Z',
  },
  {
    id: 'branch-dbn-c',
    name: 'Durban Central',
    code: 'DBN-C',
    province: 'KwaZulu-Natal',
    city: 'Durban',
    address: '77 Gateway Theatre of Shopping, 1 Palm Blvd, Umhlanga, 4319',
    phone: '+27 31 234 7001',
    email: 'umhlanga@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 295,
    revenue: 1180000,
    createdAt: '2024-02-15T08:00:00Z',
  },
  {
    id: 'branch-dbn-s',
    name: 'Durban South',
    code: 'DBN-S',
    province: 'KwaZulu-Natal',
    city: 'Durban',
    address: '33 Galleria Mall, Arbour Crossing, Amanzimtot, 4126',
    phone: '+27 31 234 7002',
    email: 'amanzimtot@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 132,
    revenue: 510000,
    createdAt: '2024-05-20T08:00:00Z',
  },
  {
    id: 'branch-pta-c',
    name: 'Pretoria Central',
    code: 'PTA-C',
    province: 'Gauteng',
    city: 'Pretoria',
    address: '61 Menlyn Park Shopping Centre, Atterbury Rd, Menlo Park, 0063',
    phone: '+27 12 234 8001',
    email: 'menlyn@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 278,
    revenue: 1050000,
    createdAt: '2024-01-25T08:00:00Z',
  },
  {
    id: 'branch-pta-e',
    name: 'Pretoria East',
    code: 'PTA-E',
    province: 'Gauteng',
    city: 'Pretoria',
    address: '15 Brooklyn Mall, Fehrsen St, New Muckleneuk, 0181',
    phone: '+27 12 234 8002',
    email: 'brooklyn@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 145,
    revenue: 580000,
    createdAt: '2024-06-01T08:00:00Z',
  },
  {
    id: 'branch-pe-c',
    name: 'Port Elizabeth Central',
    code: 'PE-C',
    province: 'Eastern Cape',
    city: 'Gqeberha',
    address: '90 Baywest Mall, Walker Dr, Greenacres, Gqeberha, 6045',
    phone: '+27 41 234 9001',
    email: 'baywest@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 167,
    revenue: 640000,
    createdAt: '2024-03-20T08:00:00Z',
  },
  {
    id: 'branch-bfn-c',
    name: 'Bloemfontein Central',
    code: 'BFN-C',
    province: 'Free State',
    city: 'Bloemfontein',
    address: '28 Mimosa Mall, 21 Markgraaff St, Dan Pienaar, Bloemfontein, 9301',
    phone: '+27 51 234 1001',
    email: 'bloemfontein@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 98,
    revenue: 380000,
    createdAt: '2024-04-15T08:00:00Z',
  },
  {
    id: 'branch-nlp-c',
    name: 'Nelspruit Central',
    code: 'NLP-C',
    province: 'Mpumalanga',
    city: 'Mbombela',
    address: '44 Riverside Mall, N4, Riverside, Mbombela, 1200',
    phone: '+27 13 234 2001',
    email: 'nelspruit@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 112,
    revenue: 420000,
    createdAt: '2024-05-01T08:00:00Z',
  },
  {
    id: 'branch-pkw-c',
    name: 'Polokwane Central',
    code: 'PKW-C',
    province: 'Limpopo',
    city: 'Polokwane',
    address: '19 Mall of the North, R71, Bendor, Polokwane, 0699',
    phone: '+27 15 234 3001',
    email: 'polokwane@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 87,
    revenue: 310000,
    createdAt: '2024-06-10T08:00:00Z',
  },
  {
    id: 'branch-eln-c',
    name: 'East London Central',
    code: 'ELN-C',
    province: 'Eastern Cape',
    city: 'East London',
    address: '7 Hemingways Mall, 2 Oxford St, Vincent, East London, 5247',
    phone: '+27 43 234 4001',
    email: 'eastlondon@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 76,
    revenue: 280000,
    createdAt: '2024-07-01T08:00:00Z',
  },
  {
    id: 'branch-kim-c',
    name: 'Kimberley Central',
    code: 'KIM-C',
    province: 'Northern Cape',
    city: 'Kimberley',
    address: '3 Diamond Pavilion Mall, 15 Memorial Rd, Monument Heights, Kimberley, 8301',
    phone: '+27 53 234 5001',
    email: 'kimberley@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 54,
    revenue: 190000,
    createdAt: '2024-07-15T08:00:00Z',
  },
  {
    id: 'branch-stk-c',
    name: 'Stellenbosch Central',
    code: 'STK-C',
    province: 'Western Cape',
    city: 'Stellenbosch',
    address: '22 Die Boord Shopping Centre, R44, Stellenbosch, 7600',
    phone: '+27 21 234 6101',
    email: 'stellenbosch@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 93,
    revenue: 360000,
    createdAt: '2024-08-01T08:00:00Z',
  },
  {
    id: 'branch-gey-c',
    name: 'George Central',
    code: 'GEY-C',
    province: 'Western Cape',
    city: 'George',
    address: '11 Garden Route Mall, Knysna Rd, George South, 6529',
    phone: '+27 44 234 7001',
    email: 'george@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 68,
    revenue: 240000,
    createdAt: '2024-08-15T08:00:00Z',
  },
  {
    id: 'branch-rst-c',
    name: 'Rustenburg Central',
    code: 'RST-C',
    province: 'North West',
    city: 'Rustenburg',
    address: '9 Waterfall Mall, Kerk St, Rustenburg, 0300',
    phone: '+27 14 234 8001',
    email: 'rustenburg@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 82,
    revenue: 290000,
    createdAt: '2024-09-01T08:00:00Z',
  },
  {
    id: 'branch-vdb-c',
    name: 'Vereeniging Central',
    code: 'VDB-C',
    province: 'Gauteng',
    city: 'Vereeniging',
    address: '36 Vaal Mall, Frikkie Meyer Blvd, Vereeniging, 1930',
    phone: '+27 16 234 9001',
    email: 'vereeniging@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 71,
    revenue: 250000,
    createdAt: '2024-09-15T08:00:00Z',
  },
  {
    id: 'branch-pmb-c',
    name: 'Pietermaritzburg Central',
    code: 'PMB-C',
    province: 'KwaZulu-Natal',
    city: 'Pietermaritzburg',
    address: '14 Gateway Arena, 151 Langalibalele St, Pietermaritzburg, 3201',
    phone: '+27 33 234 1001',
    email: 'pmb@jkraffle.co.za',
    managerId: null,
    status: 'active',
    memberCount: 105,
    revenue: 390000,
    createdAt: '2024-10-01T08:00:00Z',
  },
];

// ============================================
// 2. USERS (6 demo users with different roles)
// ============================================

export const mockUsers: User[] = [
  {
    id: 'user-thabo',
    email: 'thabo@jkraffle.co.za',
    phone: '+27 82 555 1001',
    firstName: 'Thabo',
    lastName: 'Mokoena',
    avatar: null,
    occupation: 'Chief Executive Officer',
    biography: 'Thabo is the founder and CEO of JK Raffle, with over 15 years of experience in the gaming and entertainment industry across Southern Africa.',
    role: 'super_admin' as UserRole,
    status: 'active' as UserStatus,
    branchId: null,
    twoFactorEnabled: true,
    lastLoginAt: '2025-06-12T09:15:00Z',
    createdAt: '2023-06-01T08:00:00Z',
    updatedAt: '2025-06-12T09:15:00Z',
  },
  {
    id: 'user-sarah',
    email: 'sarah@jkraffle.co.za',
    phone: '+27 83 555 2002',
    firstName: 'Sarah',
    lastName: 'van der Merwe',
    avatar: null,
    occupation: 'Operations Director',
    biography: 'Sarah oversees all branch operations and campaign management. She brings 10 years of expertise in retail and raffle operations management.',
    role: 'admin' as UserRole,
    status: 'active' as UserStatus,
    branchId: null,
    twoFactorEnabled: true,
    lastLoginAt: '2025-06-11T14:30:00Z',
    createdAt: '2023-08-15T08:00:00Z',
    updatedAt: '2025-06-11T14:30:00Z',
  },
  {
    id: 'user-david',
    email: 'david@jkraffle.co.za',
    phone: '+27 84 555 3003',
    firstName: 'David',
    lastName: 'Nkosi',
    avatar: null,
    occupation: 'Branch Manager',
    biography: 'David manages the flagship Johannesburg North branch in Sandton. He has grown the branch membership by 200% since taking over in early 2024.',
    role: 'branch_manager' as UserRole,
    status: 'active' as UserStatus,
    branchId: 'branch-jhb-n',
    twoFactorEnabled: true,
    lastLoginAt: '2025-06-12T07:45:00Z',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2025-06-12T07:45:00Z',
  },
  {
    id: 'user-james',
    email: 'james.peterson@email.co.za',
    phone: '+27 85 555 4004',
    firstName: 'James',
    lastName: 'Peterson',
    avatar: null,
    occupation: 'Financial Analyst',
    biography: null,
    role: 'member' as UserRole,
    status: 'active' as UserStatus,
    branchId: 'branch-jhb-n',
    twoFactorEnabled: false,
    lastLoginAt: '2025-06-12T11:20:00Z',
    createdAt: '2024-09-22T10:30:00Z',
    updatedAt: '2025-06-12T11:20:00Z',
  },
  {
    id: 'user-lisa',
    email: 'lisa@jkraffle.co.za',
    phone: '+27 86 555 5005',
    firstName: 'Lisa',
    lastName: 'Botha',
    avatar: null,
    occupation: 'Customer Support Lead',
    biography: 'Lisa leads the customer support team, handling member queries, ticket issues, and winner verification across all branches.',
    role: 'support' as UserRole,
    status: 'active' as UserStatus,
    branchId: null,
    twoFactorEnabled: true,
    lastLoginAt: '2025-06-12T08:00:00Z',
    createdAt: '2024-02-01T08:00:00Z',
    updatedAt: '2025-06-12T08:00:00Z',
  },
  {
    id: 'user-michael',
    email: 'michael@jkraffle.co.za',
    phone: '+27 87 555 6006',
    firstName: 'Michael',
    lastName: 'Mabuza',
    avatar: null,
    occupation: 'Internal Auditor',
    biography: 'Michael ensures compliance with South African gaming regulations and oversees the integrity of all raffle draws and financial transactions.',
    role: 'auditor' as UserRole,
    status: 'active' as UserStatus,
    branchId: null,
    twoFactorEnabled: true,
    lastLoginAt: '2025-06-10T16:00:00Z',
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2025-06-10T16:00:00Z',
  },
];

// Convenience references
export const mockCurrentUser = mockUsers.find(u => u.id === 'user-james')!;
export const mockBranchManager = mockUsers.find(u => u.id === 'user-david')!;
export const mockAdmin = mockUsers.find(u => u.id === 'user-thabo')!;

// ============================================
// 3. PRODUCTS (15 across categories)
// ============================================

export const mockProducts: Product[] = [
  // Houses (3)
  {
    id: 'prod-house-1',
    name: 'Sandton Penthouse Suite',
    description: 'Luxurious 3-bedroom penthouse in the heart of Sandton with panoramic views of the Johannesburg skyline, private rooftop pool, and designer finishes throughout. 280m² of living space including a gourmet kitchen and home office.',
    category: 'house' as ProductCategory,
    value: 8500000,
    image: null,
    images: null,
    videoUrl: null,
    specs: { bedrooms: '3', bathrooms: '2.5', size: '280m²', parking: '2 garages', levies: 'R8,500/pm', erf: 'Sectional Title' },
    status: 'active',
    featured: true,
    createdAt: '2025-03-01T08:00:00Z',
  },
  {
    id: 'prod-house-2',
    name: 'Clifton Beach Villa',
    description: 'Stunning 4-bedroom luxury villa overlooking the Atlantic Ocean in exclusive Clifton, Cape Town. Features infinity pool, private lift, wine cellar, and direct beach access. A R12M prize.',
    category: 'house' as ProductCategory,
    value: 12000000,
    image: null,
    images: null,
    videoUrl: null,
    specs: { bedrooms: '4', bathrooms: '4', size: '420m²', parking: '3 garages + 2 open', pool: 'Infinity Pool', erf: '750m²' },
    status: 'active',
    featured: true,
    createdAt: '2025-04-10T08:00:00Z',
  },
  {
    id: 'prod-house-3',
    name: 'Umhlanga Coastal Apartment',
    description: 'Modern 2-bedroom apartment in Umhlanga Ridge with ocean views, located in a secure complex with gym, pool, and 24-hour security. Walking distance to Umhlanga village and beachfront.',
    category: 'house' as ProductCategory,
    value: 3200000,
    image: null,
    images: null,
    videoUrl: null,
    specs: { bedrooms: '2', bathrooms: '2', size: '145m²', parking: '1 garage + 1 open', levies: 'R4,200/pm', erf: 'Sectional Title' },
    status: 'active',
    featured: false,
    createdAt: '2025-05-15T08:00:00Z',
  },
  // Vehicles (3)
  {
    id: 'prod-vehicle-1',
    name: 'Mercedes-AMG GT 63 S',
    description: 'The ultimate performance saloon. 4.0L V8 biturbo engine producing 630hp, AMG RIDE CONTROL+ suspension, MBUX infotainment system, and AMG Performance exhaust. Finished in Selenite Grey Magno.',
    category: 'vehicle' as ProductCategory,
    value: 3250000,
    image: null,
    images: null,
    videoUrl: null,
    specs: { engine: '4.0L V8 Biturbo', power: '630hp', transmission: '9G-TRONIC AMG', acceleration: '0-100km/h in 3.2s', colour: 'Selenite Grey Magno', mileage: 'Brand New' },
    status: 'active',
    featured: true,
    createdAt: '2025-03-15T08:00:00Z',
  },
  {
    id: 'prod-vehicle-2',
    name: 'BMW X5 M Competition',
    description: 'High-performance luxury SUV with 4.4L V8 twin-turbo producing 625hp. Features M Sport exhaust, ceramic brakes, panoramic sunroof, and Harman Kardon surround sound.',
    category: 'vehicle' as ProductCategory,
    value: 2850000,
    image: null,
    images: null,
    videoUrl: null,
    specs: { engine: '4.4L V8 Twin-Turbo', power: '625hp', transmission: '8-Speed M Steptronic', acceleration: '0-100km/h in 3.7s', colour: 'Marina Bay Blue', mileage: 'Brand New' },
    status: 'active',
    featured: false,
    createdAt: '2025-04-01T08:00:00Z',
  },
  {
    id: 'prod-vehicle-3',
    name: 'Porsche 911 Carrera S',
    description: 'The iconic sports car redefined. 3.0L twin-turbocharged flat-six producing 450hp, PASM sport suspension, Sport Chrono package, and BOSE surround sound. Guards Red with black leather interior.',
    category: 'vehicle' as ProductCategory,
    value: 2450000,
    image: null,
    images: null,
    videoUrl: null,
    specs: { engine: '3.0L Twin-Turbo Flat-6', power: '450hp', transmission: '8-Speed PDK', acceleration: '0-100km/h in 3.5s', colour: 'Guards Red', mileage: 'Brand New' },
    status: 'active',
    featured: true,
    createdAt: '2025-05-01T08:00:00Z',
  },
  // Electronics (3)
  {
    id: 'prod-elec-1',
    name: 'MacBook Pro 16" M3 Max',
    description: 'Apple MacBook Pro 16-inch with M3 Max chip, 36GB unified memory, 1TB SSD storage. Space Black finish with Liquid Retina XDR display. The ultimate creative workstation.',
    category: 'electronics' as ProductCategory,
    value: 84999,
    image: null,
    images: null,
    videoUrl: null,
    specs: { chip: 'Apple M3 Max', memory: '36GB Unified', storage: '1TB SSD', display: '16.2" Liquid Retina XDR', battery: 'Up to 22 hours', colour: 'Space Black' },
    status: 'active',
    featured: false,
    createdAt: '2025-02-10T08:00:00Z',
  },
  {
    id: 'prod-elec-2',
    name: 'Samsung 85" Neo QLED 8K TV',
    description: 'Samsung 85-inch Neo QLED 8K Smart TV with Neural Quantum Processor 8K, Dolby Atmos, Object Tracking Sound, and Gaming Hub. The ultimate home cinema experience.',
    category: 'electronics' as ProductCategory,
    value: 129999,
    image: null,
    images: null,
    videoUrl: null,
    specs: { display: '85" Neo QLED 8K', processor: 'Neural Quantum 8K', hdr: 'HDR10+', sound: 'Dolby Atmos 70W', smart: 'Tizen OS', refresh: '120Hz' },
    status: 'active',
    featured: false,
    createdAt: '2025-03-05T08:00:00Z',
  },
  {
    id: 'prod-elec-3',
    name: 'Sony Alpha 1 Camera Bundle',
    description: 'Professional mirrorless camera with 50.1MP full-frame sensor, 8K video recording, and 30fps continuous shooting. Includes 24-70mm f/2.8 GM II lens and 70-200mm f/2.8 GM II lens.',
    category: 'electronics' as ProductCategory,
    value: 175000,
    image: null,
    images: null,
    videoUrl: null,
    specs: { sensor: '50.1MP Full-Frame CMOS', video: '8K 30p / 4K 120p', af: '759 Phase-Detection AF Points', stabilization: '5-Axis IBIS', lenses: '24-70mm & 70-200mm GM II', cards: 'Dual CFexpress Type A' },
    status: 'active',
    featured: false,
    createdAt: '2025-04-20T08:00:00Z',
  },
  // Cash Prizes (3)
  {
    id: 'prod-cash-1',
    name: 'R500,000 Cash Jackpot',
    description: 'A life-changing R500,000 cash prize deposited directly into the winner\'s bank account within 48 hours of draw verification. No restrictions on how you spend it!',
    category: 'cash' as ProductCategory,
    value: 500000,
    image: null,
    images: null,
    videoUrl: null,
    specs: { amount: 'R500,000', payout: 'EFT within 48 hours', tax: 'No tax on winnings under R25M', currency: 'ZAR (South African Rand)' },
    status: 'active',
    featured: true,
    createdAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'prod-cash-2',
    name: 'R250,000 Cash Prize',
    description: 'R250,000 cash prize to kickstart your dreams. Whether it\'s home renovations, a business venture, or that dream holiday — this prize gives you the freedom to choose.',
    category: 'cash' as ProductCategory,
    value: 250000,
    image: null,
    images: null,
    videoUrl: null,
    specs: { amount: 'R250,000', payout: 'EFT within 48 hours', tax: 'No tax on winnings under R25M', currency: 'ZAR (South African Rand)' },
    status: 'active',
    featured: false,
    createdAt: '2025-02-20T08:00:00Z',
  },
  {
    id: 'prod-cash-3',
    name: 'R1,000,000 Mega Cash Jackpot',
    description: 'The biggest cash prize in JK Raffle history! R1,000,000 deposited into your account. Imagine the possibilities — invest, travel, or simply enjoy financial freedom.',
    category: 'cash' as ProductCategory,
    value: 1000000,
    image: null,
    images: null,
    videoUrl: null,
    specs: { amount: 'R1,000,000', payout: 'EFT within 48 hours', tax: 'No tax on winnings under R25M', currency: 'ZAR (South African Rand)' },
    status: 'active',
    featured: true,
    createdAt: '2025-05-10T08:00:00Z',
  },
  // Vacation (3)
  {
    id: 'prod-vac-1',
    name: 'Maldives Luxury Retreat',
    description: '7-night all-inclusive stay for 2 at the 5-star Soneva Fushi Resort in the Maldives. Includes return flights from Johannesburg, private water villa, spa treatments, and water sports.',
    category: 'vacation' as ProductCategory,
    value: 350000,
    image: null,
    images: null,
    videoUrl: null,
    specs: { duration: '7 Nights', guests: '2 Adults', resort: 'Soneva Fushi 5-Star', includes: 'Flights, All-Inclusive, Spa, Water Sports', departure: 'OR Tambo, Johannesburg', validity: '12 months from draw' },
    status: 'active',
    featured: true,
    createdAt: '2025-03-20T08:00:00Z',
  },
  {
    id: 'prod-vac-2',
    name: 'Zanzibar Beach Holiday',
    description: '10-night luxury beach holiday for 2 at the Essque Zalu Zanzibar resort. Includes return flights, half-board dining, sunset dhow cruise, and Spice Island tour.',
    category: 'vacation' as ProductCategory,
    value: 120000,
    image: null,
    images: null,
    videoUrl: null,
    specs: { duration: '10 Nights', guests: '2 Adults', resort: 'Essque Zalu Zanzibar', includes: 'Flights, Half-Board, Tours', departure: 'OR Tambo, Johannesburg', validity: '12 months from draw' },
    status: 'active',
    featured: false,
    createdAt: '2025-04-05T08:00:00Z',
  },
  {
    id: 'prod-vac-3',
    name: 'Cape Winelands & Safari Combo',
    description: '14-night luxury South African experience: 5 nights in Franschhoek wine region, 3 nights Cape Town, 6 nights at Sabi Sabi Earth Lodge in Kruger. All meals, transfers, and activities included.',
    category: 'vacation' as ProductCategory,
    value: 280000,
    image: null,
    images: null,
    videoUrl: null,
    specs: { duration: '14 Nights', guests: '2 Adults', locations: 'Franschhoek, Cape Town, Sabi Sabi Kruger', includes: 'All Meals, Transfers, Game Drives, Wine Tastings', departure: 'Any SA airport', validity: '18 months from draw' },
    status: 'active',
    featured: false,
    createdAt: '2025-05-25T08:00:00Z',
  },
];

// ============================================
// Helper: get branch and product by id
// ============================================

const getBranch = (id: string): Branch => mockBranches.find(b => b.id === id)!;
const getProduct = (id: string): Product => mockProducts.find(p => p.id === id)!;

// ============================================
// 4. ACTIVE CAMPAIGNS (12 open campaigns)
// ============================================

export const mockCampaigns: Campaign[] = [
  // === 12 ACTIVE/OPEN Campaigns ===
  {
    id: 'camp-001',
    title: 'Win a Sandton Penthouse Suite',
    description: 'Stand a chance to own a stunning 3-bedroom penthouse in Sandton worth R8.5 million! This luxurious property features panoramic city views, a private rooftop pool, and world-class finishes.',
    productId: 'prod-house-1',
    product: mockProducts[0],
    branchId: 'branch-jhb-n',
    branch: getBranch('branch-jhb-n'),
    status: 'open' as CampaignStatus,
    ticketPrice: 500,
    maxTickets: 300,
    soldTickets: 234,
    drawDate: '2025-07-15T18:00:00Z',
    drawLocation: 'Sandton Convention Centre, Johannesburg',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: null,
    createdAt: '2025-04-01T08:00:00Z',
    closedAt: null,
    drawnAt: null,
    progress: 78,
  },
  {
    id: 'camp-002',
    title: 'Drive Home a Mercedes-AMG GT 63 S',
    description: 'Your dream car awaits! Win this incredible Mercedes-AMG GT 63 S worth R3.25 million. 630hp of pure German engineering excellence.',
    productId: 'prod-vehicle-1',
    product: mockProducts[3],
    branchId: 'branch-cpt-c',
    branch: getBranch('branch-cpt-c'),
    status: 'open' as CampaignStatus,
    ticketPrice: 350,
    maxTickets: 200,
    soldTickets: 162,
    drawDate: '2025-07-28T19:00:00Z',
    drawLocation: 'V&A Waterfront Amphitheatre, Cape Town',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: null,
    createdAt: '2025-04-15T08:00:00Z',
    closedAt: null,
    drawnAt: null,
    progress: 81,
  },
  {
    id: 'camp-003',
    title: 'R500,000 Cash Jackpot',
    description: 'Win R500,000 cash! No strings attached — the money is deposited directly into your bank account within 48 hours. What would you do with half a million rand?',
    productId: 'prod-cash-1',
    product: mockProducts[9],
    branchId: 'branch-dbn-c',
    branch: getBranch('branch-dbn-c'),
    status: 'open' as CampaignStatus,
    ticketPrice: 100,
    maxTickets: 500,
    soldTickets: 425,
    drawDate: '2025-06-30T17:00:00Z',
    drawLocation: 'Gateway Theatre of Shopping, Umhlanga',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: null,
    createdAt: '2025-03-01T08:00:00Z',
    closedAt: null,
    drawnAt: null,
    progress: 85,
  },
  {
    id: 'camp-004',
    title: 'Maldives Luxury Retreat for Two',
    description: 'Escape to paradise! 7 nights all-inclusive at the 5-star Soneva Fushi Resort in the Maldives. Includes return flights from Joburg, private water villa, and spa treatments.',
    productId: 'prod-vac-1',
    product: mockProducts[12],
    branchId: 'branch-pta-c',
    branch: getBranch('branch-pta-c'),
    status: 'open' as CampaignStatus,
    ticketPrice: 200,
    maxTickets: 250,
    soldTickets: 148,
    drawDate: '2025-08-10T18:30:00Z',
    drawLocation: 'Menlyn Park, Pretoria',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: null,
    createdAt: '2025-05-01T08:00:00Z',
    closedAt: null,
    drawnAt: null,
    progress: 59,
  },
  {
    id: 'camp-005',
    title: 'Porsche 911 Carrera S — Iconic Sports Car',
    description: 'The car that defined sports cars. Win a brand new Porsche 911 Carrera S in Guards Red — 450hp of driving perfection worth R2.45 million.',
    productId: 'prod-vehicle-3',
    product: mockProducts[5],
    branchId: 'branch-jhb-s',
    branch: getBranch('branch-jhb-s'),
    status: 'open' as CampaignStatus,
    ticketPrice: 300,
    maxTickets: 200,
    soldTickets: 90,
    drawDate: '2025-08-25T19:00:00Z',
    drawLocation: 'Gold Reef City, Johannesburg',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: null,
    createdAt: '2025-05-15T08:00:00Z',
    closedAt: null,
    drawnAt: null,
    progress: 45,
  },
  {
    id: 'camp-006',
    title: 'R1,000,000 Mega Cash Jackpot',
    description: 'The biggest cash prize in JK Raffle history! R1 million could be yours. Imagine the freedom — invest, travel, or simply enjoy life.',
    productId: 'prod-cash-3',
    product: mockProducts[11],
    branchId: 'branch-jhb-n',
    branch: getBranch('branch-jhb-n'),
    status: 'open' as CampaignStatus,
    ticketPrice: 200,
    maxTickets: 400,
    soldTickets: 310,
    drawDate: '2025-07-20T18:00:00Z',
    drawLocation: 'Montecasino, Fourways, Johannesburg',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: null,
    createdAt: '2025-04-20T08:00:00Z',
    closedAt: null,
    drawnAt: null,
    progress: 78,
  },
  {
    id: 'camp-007',
    title: 'Clifton Beach Villa — Cape Town Dream Home',
    description: 'Win a breathtaking 4-bedroom villa in exclusive Clifton, Cape Town worth R12 million. Infinity pool, ocean views, private lift — the ultimate South African dream.',
    productId: 'prod-house-2',
    product: mockProducts[1],
    branchId: 'branch-cpt-s',
    branch: getBranch('branch-cpt-s'),
    status: 'open' as CampaignStatus,
    ticketPrice: 500,
    maxTickets: 400,
    soldTickets: 186,
    drawDate: '2025-09-05T18:00:00Z',
    drawLocation: 'Cavendish Square, Claremont, Cape Town',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: null,
    createdAt: '2025-05-20T08:00:00Z',
    closedAt: null,
    drawnAt: null,
    progress: 47,
  },
  {
    id: 'camp-008',
    title: 'Samsung 85" Neo QLED 8K TV',
    description: 'Transform your living room with this massive 85-inch Samsung Neo QLED 8K Smart TV. Neural Quantum Processor, Dolby Atmos, and 120Hz gaming — cinema at home.',
    productId: 'prod-elec-2',
    product: mockProducts[7],
    branchId: 'branch-pe-c',
    branch: getBranch('branch-pe-c'),
    status: 'open' as CampaignStatus,
    ticketPrice: 50,
    maxTickets: 400,
    soldTickets: 340,
    drawDate: '2025-07-05T17:00:00Z',
    drawLocation: 'Baywest Mall, Gqeberha',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: null,
    createdAt: '2025-03-10T08:00:00Z',
    closedAt: null,
    drawnAt: null,
    progress: 85,
  },
  {
    id: 'camp-009',
    title: 'MacBook Pro 16" M3 Max Bundle',
    description: 'Win the ultimate creative workstation — MacBook Pro 16" M3 Max with 36GB RAM, 1TB SSD, plus AirPods Pro and Apple Magic Keyboard. Valued at R95,000 total.',
    productId: 'prod-elec-1',
    product: mockProducts[6],
    branchId: 'branch-nlp-c',
    branch: getBranch('branch-nlp-c'),
    status: 'open' as CampaignStatus,
    ticketPrice: 50,
    maxTickets: 300,
    soldTickets: 102,
    drawDate: '2025-08-15T16:00:00Z',
    drawLocation: 'Riverside Mall, Mbombela',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: null,
    createdAt: '2025-06-01T08:00:00Z',
    closedAt: null,
    drawnAt: null,
    progress: 34,
  },
  {
    id: 'camp-010',
    title: 'BMW X5 M Competition',
    description: 'Performance meets luxury in this BMW X5 M Competition. 625hp V8, ceramic brakes, and every luxury feature you can imagine. Worth R2.85 million.',
    productId: 'prod-vehicle-2',
    product: mockProducts[4],
    branchId: 'branch-bfn-c',
    branch: getBranch('branch-bfn-c'),
    status: 'open' as CampaignStatus,
    ticketPrice: 250,
    maxTickets: 200,
    soldTickets: 128,
    drawDate: '2025-08-30T18:00:00Z',
    drawLocation: 'Mimosa Mall, Bloemfontein',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: null,
    createdAt: '2025-05-25T08:00:00Z',
    closedAt: null,
    drawnAt: null,
    progress: 64,
  },
  {
    id: 'camp-011',
    title: 'Cape Winelands & Safari Luxury Combo',
    description: '14 nights of pure South African luxury: Franschhoek wine region, Cape Town, and Sabi Sabi in Kruger National Park. All-inclusive for 2 people.',
    productId: 'prod-vac-3',
    product: mockProducts[14],
    branchId: 'branch-stk-c',
    branch: getBranch('branch-stk-c'),
    status: 'open' as CampaignStatus,
    ticketPrice: 150,
    maxTickets: 250,
    soldTickets: 88,
    drawDate: '2025-09-15T17:00:00Z',
    drawLocation: 'Spier Wine Farm, Stellenbosch',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: null,
    createdAt: '2025-06-05T08:00:00Z',
    closedAt: null,
    drawnAt: null,
    progress: 35,
  },
  {
    id: 'camp-012',
    title: 'R250,000 Cash Prize',
    description: 'A quarter million rand could change everything! Pay off debt, start a side business, or treat yourself. This flexible cash prize is wired to your account.',
    productId: 'prod-cash-2',
    product: mockProducts[10],
    branchId: 'branch-pkw-c',
    branch: getBranch('branch-pkw-c'),
    status: 'open' as CampaignStatus,
    ticketPrice: 75,
    maxTickets: 350,
    soldTickets: 175,
    drawDate: '2025-07-10T17:30:00Z',
    drawLocation: 'Mall of the North, Polokwane',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: null,
    createdAt: '2025-04-10T08:00:00Z',
    closedAt: null,
    drawnAt: null,
    progress: 50,
  },

  // === 6 COMPLETED Campaigns ===
  {
    id: 'camp-c01',
    title: 'Umhlanga Coastal Apartment Raffle',
    description: 'Congratulations to the winner of this beautiful 2-bedroom apartment in Umhlanga Ridge! The draw was conducted live at Gateway Theatre of Shopping.',
    productId: 'prod-house-3',
    product: mockProducts[2],
    branchId: 'branch-dbn-c',
    branch: getBranch('branch-dbn-c'),
    status: 'completed' as CampaignStatus,
    ticketPrice: 300,
    maxTickets: 200,
    soldTickets: 200,
    drawDate: '2025-03-15T18:00:00Z',
    drawLocation: 'Gateway Theatre of Shopping, Umhlanga',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: 'winner-nompumelelo',
    createdAt: '2024-12-01T08:00:00Z',
    closedAt: '2025-03-15T18:05:00Z',
    drawnAt: '2025-03-15T18:05:00Z',
    progress: 100,
  },
  {
    id: 'camp-c02',
    title: 'Sony Alpha 1 Camera Bundle',
    description: 'A professional photographer\'s dream setup! The Sony Alpha 1 with two premium G Master lenses was won by a lucky photographer from Cape Town.',
    productId: 'prod-elec-3',
    product: mockProducts[8],
    branchId: 'branch-cpt-c',
    branch: getBranch('branch-cpt-c'),
    status: 'completed' as CampaignStatus,
    ticketPrice: 100,
    maxTickets: 250,
    soldTickets: 250,
    drawDate: '2025-02-28T17:00:00Z',
    drawLocation: 'V&A Waterfront, Cape Town',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: 'winner-aarav',
    createdAt: '2024-11-15T08:00:00Z',
    closedAt: '2025-02-28T17:05:00Z',
    drawnAt: '2025-02-28T17:05:00Z',
    progress: 100,
  },
  {
    id: 'camp-c03',
    title: 'Zanzibar Beach Holiday Raffle',
    description: 'Two lucky winners enjoyed a 10-night luxury holiday in Zanzibar! The draw took place at Menlyn Park Shopping Centre.',
    productId: 'prod-vac-2',
    product: mockProducts[13],
    branchId: 'branch-pta-c',
    branch: getBranch('branch-pta-c'),
    status: 'completed' as CampaignStatus,
    ticketPrice: 75,
    maxTickets: 300,
    soldTickets: 300,
    drawDate: '2025-04-20T18:00:00Z',
    drawLocation: 'Menlyn Park, Pretoria',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: 'winner-thandiwe',
    createdAt: '2025-01-10T08:00:00Z',
    closedAt: '2025-04-20T18:05:00Z',
    drawnAt: '2025-04-20T18:05:00Z',
    progress: 100,
  },
  {
    id: 'camp-c04',
    title: 'R200,000 Cash Bonanza',
    description: 'A cash prize of R200,000 was won by a regular JK Raffle member from Johannesburg. The prize was deposited within 24 hours of verification.',
    productId: 'prod-cash-2',
    product: mockProducts[10],
    branchId: 'branch-jhb-n',
    branch: getBranch('branch-jhb-n'),
    status: 'completed' as CampaignStatus,
    ticketPrice: 50,
    maxTickets: 400,
    soldTickets: 400,
    drawDate: '2025-01-31T17:00:00Z',
    drawLocation: 'Sandton City, Johannesburg',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: 'winner-sipho',
    createdAt: '2024-10-01T08:00:00Z',
    closedAt: '2025-01-31T17:05:00Z',
    drawnAt: '2025-01-31T17:05:00Z',
    progress: 100,
  },
  {
    id: 'camp-c05',
    title: 'Mercedes-AMG A45 S Raffle',
    description: 'The hot hatch of dreams! A Mercedes-AMG A45 S worth R1.2 million was won by an ecstatic member from Durban.',
    productId: 'prod-vehicle-1',
    product: mockProducts[3],
    branchId: 'branch-dbn-s',
    branch: getBranch('branch-dbn-s'),
    status: 'completed' as CampaignStatus,
    ticketPrice: 200,
    maxTickets: 150,
    soldTickets: 150,
    drawDate: '2025-05-10T18:00:00Z',
    drawLocation: 'Galleria Mall, Amanzimtot',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: 'winner-fatima',
    createdAt: '2025-02-01T08:00:00Z',
    closedAt: '2025-05-10T18:05:00Z',
    drawnAt: '2025-05-10T18:05:00Z',
    progress: 100,
  },
  {
    id: 'camp-c06',
    title: 'R750,000 Cash Grand Prize',
    description: 'Our biggest cash draw to date! R750,000 was won by a first-time JK Raffle member from Port Elizabeth. Talk about beginner\'s luck!',
    productId: 'prod-cash-3',
    product: mockProducts[11],
    branchId: 'branch-pe-c',
    branch: getBranch('branch-pe-c'),
    status: 'completed' as CampaignStatus,
    ticketPrice: 150,
    maxTickets: 500,
    soldTickets: 500,
    drawDate: '2025-05-25T17:00:00Z',
    drawLocation: 'Baywest Mall, Gqeberha',
    featuredImage: null,
    galleryImages: null,
    videoUrl: null,
    winnerId: 'winner-bradley',
    createdAt: '2025-01-20T08:00:00Z',
    closedAt: '2025-05-25T17:05:00Z',
    drawnAt: '2025-05-25T17:05:00Z',
    progress: 100,
  },
];

// ============================================
// 6. TICKETS (50 tickets)
// ============================================

const ticketStatuses: TicketStatus[] = ['active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'active', 'won', 'won', 'won', 'won', 'won', 'won', 'expired', 'expired', 'expired', 'expired', 'expired', 'claimed', 'claimed', 'claimed', 'voided', 'voided', 'active'];

export const mockTickets: Ticket[] = [
  // Tickets for camp-001 (Sandton Penthouse) - Active
  { id: 'tkt-001', reference: 'JKR-SPH-012', campaignId: 'camp-001', userId: 'user-james', orderId: 'ord-001', status: 'active', qrCode: 'qr_sph_012', barcode: 'BC-SPH-012', verifiedAt: null, purchasedAt: '2025-04-05T10:30:00Z', createdAt: '2025-04-05T10:30:00Z' },
  { id: 'tkt-002', reference: 'JKR-SPH-047', campaignId: 'camp-001', userId: 'user-james', orderId: 'ord-001', status: 'active', qrCode: 'qr_sph_047', barcode: 'BC-SPH-047', verifiedAt: null, purchasedAt: '2025-04-05T10:30:00Z', createdAt: '2025-04-05T10:30:00Z' },
  { id: 'tkt-003', reference: 'JKR-SPH-089', campaignId: 'camp-001', userId: 'user-james', orderId: 'ord-002', status: 'active', qrCode: 'qr_sph_089', barcode: 'BC-SPH-089', verifiedAt: null, purchasedAt: '2025-04-20T14:15:00Z', createdAt: '2025-04-20T14:15:00Z' },
  { id: 'tkt-004', reference: 'JKR-SPH-156', campaignId: 'camp-001', userId: 'user-james', orderId: 'ord-003', status: 'active', qrCode: 'qr_sph_156', barcode: 'BC-SPH-156', verifiedAt: null, purchasedAt: '2025-05-10T09:00:00Z', createdAt: '2025-05-10T09:00:00Z' },
  { id: 'tkt-005', reference: 'JKR-SPH-201', campaignId: 'camp-001', userId: 'user-james', orderId: 'ord-003', status: 'active', qrCode: 'qr_sph_201', barcode: 'BC-SPH-201', verifiedAt: null, purchasedAt: '2025-05-10T09:00:00Z', createdAt: '2025-05-10T09:00:00Z' },
  // Tickets for camp-002 (Mercedes-AMG) - Active
  { id: 'tkt-006', reference: 'JKR-AMG-033', campaignId: 'camp-002', userId: 'user-james', orderId: 'ord-004', status: 'active', qrCode: 'qr_amg_033', barcode: 'BC-AMG-033', verifiedAt: null, purchasedAt: '2025-04-22T16:45:00Z', createdAt: '2025-04-22T16:45:00Z' },
  { id: 'tkt-007', reference: 'JKR-AMG-078', campaignId: 'camp-002', userId: 'user-james', orderId: 'ord-004', status: 'active', qrCode: 'qr_amg_078', barcode: 'BC-AMG-078', verifiedAt: null, purchasedAt: '2025-04-22T16:45:00Z', createdAt: '2025-04-22T16:45:00Z' },
  { id: 'tkt-008', reference: 'JKR-AMG-112', campaignId: 'camp-002', userId: 'user-james', orderId: 'ord-005', status: 'active', qrCode: 'qr_amg_112', barcode: 'BC-AMG-112', verifiedAt: null, purchasedAt: '2025-05-08T11:20:00Z', createdAt: '2025-05-08T11:20:00Z' },
  // Tickets for camp-003 (R500K Cash) - Active
  { id: 'tkt-009', reference: 'JKR-CSH-001', campaignId: 'camp-003', userId: 'user-james', orderId: 'ord-006', status: 'active', qrCode: 'qr_csh_001', barcode: 'BC-CSH-001', verifiedAt: null, purchasedAt: '2025-03-05T08:30:00Z', createdAt: '2025-03-05T08:30:00Z' },
  { id: 'tkt-010', reference: 'JKR-CSH-045', campaignId: 'camp-003', userId: 'user-james', orderId: 'ord-006', status: 'active', qrCode: 'qr_csh_045', barcode: 'BC-CSH-045', verifiedAt: null, purchasedAt: '2025-03-05T08:30:00Z', createdAt: '2025-03-05T08:30:00Z' },
  { id: 'tkt-011', reference: 'JKR-CSH-088', campaignId: 'camp-003', userId: 'user-james', orderId: 'ord-007', status: 'active', qrCode: 'qr_csh_088', barcode: 'BC-CSH-088', verifiedAt: null, purchasedAt: '2025-04-12T13:00:00Z', createdAt: '2025-04-12T13:00:00Z' },
  { id: 'tkt-012', reference: 'JKR-CSH-134', campaignId: 'camp-003', userId: 'user-james', orderId: 'ord-007', status: 'active', qrCode: 'qr_csh_134', barcode: 'BC-CSH-134', verifiedAt: null, purchasedAt: '2025-04-12T13:00:00Z', createdAt: '2025-04-12T13:00:00Z' },
  { id: 'tkt-013', reference: 'JKR-CSH-201', campaignId: 'camp-003', userId: 'user-james', orderId: 'ord-008', status: 'active', qrCode: 'qr_csh_201', barcode: 'BC-CSH-201', verifiedAt: null, purchasedAt: '2025-05-20T15:30:00Z', createdAt: '2025-05-20T15:30:00Z' },
  // Tickets for camp-004 (Maldives) - Active
  { id: 'tkt-014', reference: 'JKR-MLD-019', campaignId: 'camp-004', userId: 'user-james', orderId: 'ord-009', status: 'active', qrCode: 'qr_mld_019', barcode: 'BC-MLD-019', verifiedAt: null, purchasedAt: '2025-05-10T10:00:00Z', createdAt: '2025-05-10T10:00:00Z' },
  { id: 'tkt-015', reference: 'JKR-MLD-056', campaignId: 'camp-004', userId: 'user-james', orderId: 'ord-009', status: 'active', qrCode: 'qr_mld_056', barcode: 'BC-MLD-056', verifiedAt: null, purchasedAt: '2025-05-10T10:00:00Z', createdAt: '2025-05-10T10:00:00Z' },
  { id: 'tkt-016', reference: 'JKR-MLD-098', campaignId: 'camp-004', userId: 'user-james', orderId: 'ord-010', status: 'active', qrCode: 'qr_mld_098', barcode: 'BC-MLD-098', verifiedAt: null, purchasedAt: '2025-06-01T12:15:00Z', createdAt: '2025-06-01T12:15:00Z' },
  // Tickets for camp-006 (R1M Mega Cash) - Active
  { id: 'tkt-017', reference: 'JKR-MEG-007', campaignId: 'camp-006', userId: 'user-james', orderId: 'ord-011', status: 'active', qrCode: 'qr_meg_007', barcode: 'BC-MEG-007', verifiedAt: null, purchasedAt: '2025-04-25T09:30:00Z', createdAt: '2025-04-25T09:30:00Z' },
  { id: 'tkt-018', reference: 'JKR-MEG-051', campaignId: 'camp-006', userId: 'user-james', orderId: 'ord-011', status: 'active', qrCode: 'qr_meg_051', barcode: 'BC-MEG-051', verifiedAt: null, purchasedAt: '2025-04-25T09:30:00Z', createdAt: '2025-04-25T09:30:00Z' },
  { id: 'tkt-019', reference: 'JKR-MEG-089', campaignId: 'camp-006', userId: 'user-james', orderId: 'ord-012', status: 'active', qrCode: 'qr_meg_089', barcode: 'BC-MEG-089', verifiedAt: null, purchasedAt: '2025-05-15T14:45:00Z', createdAt: '2025-05-15T14:45:00Z' },
  // Tickets for camp-008 (Samsung TV) - Active
  { id: 'tkt-020', reference: 'JKR-TVC-023', campaignId: 'camp-008', userId: 'user-james', orderId: 'ord-013', status: 'active', qrCode: 'qr_tvc_023', barcode: 'BC-TVC-023', verifiedAt: null, purchasedAt: '2025-03-20T11:00:00Z', createdAt: '2025-03-20T11:00:00Z' },
  { id: 'tkt-021', reference: 'JKR-TVC-067', campaignId: 'camp-008', userId: 'user-james', orderId: 'ord-013', status: 'active', qrCode: 'qr_tvc_067', barcode: 'BC-TVC-067', verifiedAt: null, purchasedAt: '2025-03-20T11:00:00Z', createdAt: '2025-03-20T11:00:00Z' },
  { id: 'tkt-022', reference: 'JKR-TVC-088', campaignId: 'camp-008', userId: 'user-james', orderId: 'ord-013', status: 'active', qrCode: 'qr_tvc_088', barcode: 'BC-TVC-088', verifiedAt: null, purchasedAt: '2025-03-20T11:00:00Z', createdAt: '2025-03-20T11:00:00Z' },
  { id: 'tkt-023', reference: 'JKR-TVC-145', campaignId: 'camp-008', userId: 'user-james', orderId: 'ord-014', status: 'active', qrCode: 'qr_tvc_145', barcode: 'BC-TVC-145', verifiedAt: null, purchasedAt: '2025-04-28T16:30:00Z', createdAt: '2025-04-28T16:30:00Z' },
  // Tickets for camp-005 (Porsche) - Active
  { id: 'tkt-024', reference: 'JKR-911-015', campaignId: 'camp-005', userId: 'user-james', orderId: 'ord-015', status: 'active', qrCode: 'qr_911_015', barcode: 'BC-911-015', verifiedAt: null, purchasedAt: '2025-05-20T08:45:00Z', createdAt: '2025-05-20T08:45:00Z' },
  { id: 'tkt-025', reference: 'JKR-911-042', campaignId: 'camp-005', userId: 'user-james', orderId: 'ord-015', status: 'active', qrCode: 'qr_911_042', barcode: 'BC-911-042', verifiedAt: null, purchasedAt: '2025-05-20T08:45:00Z', createdAt: '2025-05-20T08:45:00Z' },
  // Tickets for camp-012 (R250K Cash) - Active
  { id: 'tkt-026', reference: 'JKR-QTR-034', campaignId: 'camp-012', userId: 'user-james', orderId: 'ord-016', status: 'active', qrCode: 'qr_qtr_034', barcode: 'BC-QTR-034', verifiedAt: null, purchasedAt: '2025-05-05T10:15:00Z', createdAt: '2025-05-05T10:15:00Z' },
  { id: 'tkt-027', reference: 'JKR-QTR-078', campaignId: 'camp-012', userId: 'user-james', orderId: 'ord-016', status: 'active', qrCode: 'qr_qtr_078', barcode: 'BC-QTR-078', verifiedAt: null, purchasedAt: '2025-05-05T10:15:00Z', createdAt: '2025-05-05T10:15:00Z' },
  { id: 'tkt-028', reference: 'JKR-QTR-112', campaignId: 'camp-012', userId: 'user-james', orderId: 'ord-017', status: 'active', qrCode: 'qr_qtr_112', barcode: 'BC-QTR-112', verifiedAt: null, purchasedAt: '2025-06-02T09:30:00Z', createdAt: '2025-06-02T09:30:00Z' },
  // Tickets for camp-009 (MacBook) - Active
  { id: 'tkt-029', reference: 'JKR-MAC-011', campaignId: 'camp-009', userId: 'user-james', orderId: 'ord-018', status: 'active', qrCode: 'qr_mac_011', barcode: 'BC-MAC-011', verifiedAt: null, purchasedAt: '2025-06-05T14:00:00Z', createdAt: '2025-06-05T14:00:00Z' },
  { id: 'tkt-030', reference: 'JKR-MAC-045', campaignId: 'camp-009', userId: 'user-james', orderId: 'ord-018', status: 'active', qrCode: 'qr_mac_045', barcode: 'BC-MAC-045', verifiedAt: null, purchasedAt: '2025-06-05T14:00:00Z', createdAt: '2025-06-05T14:00:00Z' },
  { id: 'tkt-031', reference: 'JKR-MAC-067', campaignId: 'camp-009', userId: 'user-james', orderId: 'ord-018', status: 'active', qrCode: 'qr_mac_067', barcode: 'BC-MAC-067', verifiedAt: null, purchasedAt: '2025-06-05T14:00:00Z', createdAt: '2025-06-05T14:00:00Z' },
  // --- TICKETS FOR COMPLETED CAMPAIGNS ---
  // camp-c01 (Umhlanga Apartment) - Winner ticket
  { id: 'tkt-032', reference: 'JKR-UMH-187', campaignId: 'camp-c01', userId: 'winner-nompumelelo', orderId: 'ord-c01', status: 'won', qrCode: 'qr_umh_187', barcode: 'BC-UMH-187', verifiedAt: '2025-03-15T18:10:00Z', purchasedAt: '2025-01-10T12:00:00Z', createdAt: '2025-01-10T12:00:00Z' },
  // camp-c02 (Sony Camera) - Winner ticket
  { id: 'tkt-033', reference: 'JKR-CAM-098', campaignId: 'camp-c02', userId: 'winner-aarav', orderId: 'ord-c02', status: 'claimed', qrCode: 'qr_cam_098', barcode: 'BC-CAM-098', verifiedAt: '2025-02-28T17:10:00Z', purchasedAt: '2025-01-05T10:30:00Z', createdAt: '2025-01-05T10:30:00Z' },
  // camp-c03 (Zanzibar) - Winner ticket
  { id: 'tkt-034', reference: 'JKR-ZNZ-234', campaignId: 'camp-c03', userId: 'winner-thandiwe', orderId: 'ord-c03', status: 'claimed', qrCode: 'qr_znz_234', barcode: 'BC-ZNZ-234', verifiedAt: '2025-04-20T18:10:00Z', purchasedAt: '2025-02-14T09:45:00Z', createdAt: '2025-02-14T09:45:00Z' },
  // camp-c04 (R200K Cash) - Winner ticket
  { id: 'tkt-035', reference: 'JKR-CS2-312', campaignId: 'camp-c04', userId: 'winner-sipho', orderId: 'ord-c04', status: 'claimed', qrCode: 'qr_cs2_312', barcode: 'BC-CS2-312', verifiedAt: '2025-01-31T17:10:00Z', purchasedAt: '2024-12-05T15:00:00Z', createdAt: '2024-12-05T15:00:00Z' },
  // camp-c05 (AMG A45 S) - Winner ticket
  { id: 'tkt-036', reference: 'JKR-A45-087', campaignId: 'camp-c05', userId: 'winner-fatima', orderId: 'ord-c05', status: 'won', qrCode: 'qr_a45_087', barcode: 'BC-A45-087', verifiedAt: '2025-05-10T18:10:00Z', purchasedAt: '2025-02-20T11:30:00Z', createdAt: '2025-02-20T11:30:00Z' },
  // camp-c06 (R750K Cash) - Winner ticket
  { id: 'tkt-037', reference: 'JKR-75K-445', campaignId: 'camp-c06', userId: 'winner-bradley', orderId: 'ord-c06', status: 'won', qrCode: 'qr_75k_445', barcode: 'BC-75K-445', verifiedAt: '2025-05-25T17:10:00Z', purchasedAt: '2025-03-01T08:15:00Z', createdAt: '2025-03-01T08:15:00Z' },
  // Expired tickets from completed campaigns
  { id: 'tkt-038', reference: 'JKR-UMH-045', campaignId: 'camp-c01', userId: 'user-james', orderId: 'ord-c07', status: 'expired', qrCode: 'qr_umh_045', barcode: 'BC-UMH-045', verifiedAt: null, purchasedAt: '2024-12-15T10:00:00Z', createdAt: '2024-12-15T10:00:00Z' },
  { id: 'tkt-039', reference: 'JKR-UMH-112', campaignId: 'camp-c01', userId: 'user-james', orderId: 'ord-c07', status: 'expired', qrCode: 'qr_umh_112', barcode: 'BC-UMH-112', verifiedAt: null, purchasedAt: '2024-12-15T10:00:00Z', createdAt: '2024-12-15T10:00:00Z' },
  { id: 'tkt-040', reference: 'JKR-CS2-156', campaignId: 'camp-c04', userId: 'user-james', orderId: 'ord-c08', status: 'expired', qrCode: 'qr_cs2_156', barcode: 'BC-CS2-156', verifiedAt: null, purchasedAt: '2024-11-20T14:30:00Z', createdAt: '2024-11-20T14:30:00Z' },
  { id: 'tkt-041', reference: 'JKR-CS2-201', campaignId: 'camp-c04', userId: 'user-james', orderId: 'ord-c08', status: 'expired', qrCode: 'qr_cs2_201', barcode: 'BC-CS2-201', verifiedAt: null, purchasedAt: '2024-11-20T14:30:00Z', createdAt: '2024-11-20T14:30:00Z' },
  { id: 'tkt-042', reference: 'JKR-CS2-278', campaignId: 'camp-c04', userId: 'user-james', orderId: 'ord-c09', status: 'expired', qrCode: 'qr_cs2_278', barcode: 'BC-CS2-278', verifiedAt: null, purchasedAt: '2025-01-05T09:00:00Z', createdAt: '2025-01-05T09:00:00Z' },
  { id: 'tkt-043', reference: 'JKR-CAM-045', campaignId: 'camp-c02', userId: 'user-james', orderId: 'ord-c10', status: 'expired', qrCode: 'qr_cam_045', barcode: 'BC-CAM-045', verifiedAt: null, purchasedAt: '2024-12-10T16:00:00Z', createdAt: '2024-12-10T16:00:00Z' },
  { id: 'tkt-044', reference: 'JKR-CAM-178', campaignId: 'camp-c02', userId: 'user-james', orderId: 'ord-c10', status: 'expired', qrCode: 'qr_cam_178', barcode: 'BC-CAM-178', verifiedAt: null, purchasedAt: '2024-12-10T16:00:00Z', createdAt: '2024-12-10T16:00:00Z' },
  // Voided tickets (refunded)
  { id: 'tkt-045', reference: 'JKR-SPH-023', campaignId: 'camp-001', userId: 'user-james', orderId: 'ord-019', status: 'voided', qrCode: null, barcode: null, verifiedAt: null, purchasedAt: '2025-04-10T08:00:00Z', createdAt: '2025-04-10T08:00:00Z' },
  { id: 'tkt-046', reference: 'JKR-AMG-045', campaignId: 'camp-002', userId: 'user-james', orderId: 'ord-020', status: 'voided', qrCode: null, barcode: null, verifiedAt: null, purchasedAt: '2025-04-18T12:00:00Z', createdAt: '2025-04-18T12:00:00Z' },
  // Additional active tickets for camp-007, camp-010, camp-011
  { id: 'tkt-047', reference: 'JKR-CLF-034', campaignId: 'camp-007', userId: 'user-james', orderId: null, status: 'active', qrCode: 'qr_clf_034', barcode: 'BC-CLF-034', verifiedAt: null, purchasedAt: '2025-05-28T10:00:00Z', createdAt: '2025-05-28T10:00:00Z' },
  { id: 'tkt-048', reference: 'JKR-BMW-056', campaignId: 'camp-010', userId: 'user-james', orderId: null, status: 'active', qrCode: 'qr_bmw_056', barcode: 'BC-BMW-056', verifiedAt: null, purchasedAt: '2025-06-03T11:30:00Z', createdAt: '2025-06-03T11:30:00Z' },
  { id: 'tkt-049', reference: 'JKR-WNL-022', campaignId: 'camp-011', userId: 'user-james', orderId: null, status: 'active', qrCode: 'qr_wnl_022', barcode: 'BC-WNL-022', verifiedAt: null, purchasedAt: '2025-06-08T15:00:00Z', createdAt: '2025-06-08T15:00:00Z' },
  { id: 'tkt-050', reference: 'JKR-WNL-045', campaignId: 'camp-011', userId: 'user-james', orderId: null, status: 'active', qrCode: 'qr_wnl_045', barcode: 'BC-WNL-045', verifiedAt: null, purchasedAt: '2025-06-08T15:00:00Z', createdAt: '2025-06-08T15:00:00Z' },
];

// ============================================
// 7. ORDERS (20 orders)
// ============================================

export const mockOrders: Order[] = [
  { id: 'ord-001', userId: 'user-james', campaignId: 'camp-001', ticketCount: 2, totalAmount: 1000, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-04-05T10:30:00Z', createdAt: '2025-04-05T10:28:00Z' },
  { id: 'ord-002', userId: 'user-james', campaignId: 'camp-001', ticketCount: 1, totalAmount: 500, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-04-20T14:15:00Z', createdAt: '2025-04-20T14:12:00Z' },
  { id: 'ord-003', userId: 'user-james', campaignId: 'camp-001', ticketCount: 2, totalAmount: 1000, status: 'paid' as OrderStatus, paymentMethod: 'eft', paidAt: '2025-05-10T09:00:00Z', createdAt: '2025-05-09T16:00:00Z' },
  { id: 'ord-004', userId: 'user-james', campaignId: 'camp-002', ticketCount: 2, totalAmount: 700, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-04-22T16:45:00Z', createdAt: '2025-04-22T16:42:00Z' },
  { id: 'ord-005', userId: 'user-james', campaignId: 'camp-002', ticketCount: 1, totalAmount: 350, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-05-08T11:20:00Z', createdAt: '2025-05-08T11:18:00Z' },
  { id: 'ord-006', userId: 'user-james', campaignId: 'camp-003', ticketCount: 2, totalAmount: 200, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-03-05T08:30:00Z', createdAt: '2025-03-05T08:28:00Z' },
  { id: 'ord-007', userId: 'user-james', campaignId: 'camp-003', ticketCount: 2, totalAmount: 200, status: 'paid' as OrderStatus, paymentMethod: 'eft', paidAt: '2025-04-12T13:00:00Z', createdAt: '2025-04-11T10:00:00Z' },
  { id: 'ord-008', userId: 'user-james', campaignId: 'camp-003', ticketCount: 1, totalAmount: 100, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-05-20T15:30:00Z', createdAt: '2025-05-20T15:28:00Z' },
  { id: 'ord-009', userId: 'user-james', campaignId: 'camp-004', ticketCount: 2, totalAmount: 400, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-05-10T10:00:00Z', createdAt: '2025-05-10T09:55:00Z' },
  { id: 'ord-010', userId: 'user-james', campaignId: 'camp-004', ticketCount: 1, totalAmount: 200, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-06-01T12:15:00Z', createdAt: '2025-06-01T12:12:00Z' },
  { id: 'ord-011', userId: 'user-james', campaignId: 'camp-006', ticketCount: 2, totalAmount: 400, status: 'paid' as OrderStatus, paymentMethod: 'eft', paidAt: '2025-04-25T09:30:00Z', createdAt: '2025-04-24T14:00:00Z' },
  { id: 'ord-012', userId: 'user-james', campaignId: 'camp-006', ticketCount: 1, totalAmount: 200, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-05-15T14:45:00Z', createdAt: '2025-05-15T14:42:00Z' },
  { id: 'ord-013', userId: 'user-james', campaignId: 'camp-008', ticketCount: 3, totalAmount: 150, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-03-20T11:00:00Z', createdAt: '2025-03-20T10:58:00Z' },
  { id: 'ord-014', userId: 'user-james', campaignId: 'camp-008', ticketCount: 1, totalAmount: 50, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-04-28T16:30:00Z', createdAt: '2025-04-28T16:28:00Z' },
  { id: 'ord-015', userId: 'user-james', campaignId: 'camp-005', ticketCount: 2, totalAmount: 600, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-05-20T08:45:00Z', createdAt: '2025-05-20T08:42:00Z' },
  { id: 'ord-016', userId: 'user-james', campaignId: 'camp-012', ticketCount: 2, totalAmount: 150, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-05-05T10:15:00Z', createdAt: '2025-05-05T10:12:00Z' },
  { id: 'ord-017', userId: 'user-james', campaignId: 'camp-012', ticketCount: 1, totalAmount: 75, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-06-02T09:30:00Z', createdAt: '2025-06-02T09:28:00Z' },
  { id: 'ord-018', userId: 'user-james', campaignId: 'camp-009', ticketCount: 3, totalAmount: 150, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-06-05T14:00:00Z', createdAt: '2025-06-05T13:58:00Z' },
  // Refunded orders
  { id: 'ord-019', userId: 'user-james', campaignId: 'camp-001', ticketCount: 1, totalAmount: 500, status: 'refunded' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-04-10T08:00:00Z', createdAt: '2025-04-10T07:55:00Z' },
  { id: 'ord-020', userId: 'user-james', campaignId: 'camp-002', ticketCount: 1, totalAmount: 350, status: 'refunded' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-04-18T12:00:00Z', createdAt: '2025-04-18T11:55:00Z' },
  // Completed campaign orders (for winners and past tickets)
  { id: 'ord-c01', userId: 'winner-nompumelelo', campaignId: 'camp-c01', ticketCount: 1, totalAmount: 300, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-01-10T12:00:00Z', createdAt: '2025-01-10T11:55:00Z' },
  { id: 'ord-c02', userId: 'winner-aarav', campaignId: 'camp-c02', ticketCount: 1, totalAmount: 100, status: 'paid' as OrderStatus, paymentMethod: 'eft', paidAt: '2025-01-05T10:30:00Z', createdAt: '2025-01-05T10:25:00Z' },
  { id: 'ord-c03', userId: 'winner-thandiwe', campaignId: 'camp-c03', ticketCount: 1, totalAmount: 75, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-02-14T09:45:00Z', createdAt: '2025-02-14T09:40:00Z' },
  { id: 'ord-c04', userId: 'winner-sipho', campaignId: 'camp-c04', ticketCount: 1, totalAmount: 50, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2024-12-05T15:00:00Z', createdAt: '2024-12-05T14:55:00Z' },
  { id: 'ord-c05', userId: 'winner-fatima', campaignId: 'camp-c05', ticketCount: 1, totalAmount: 200, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-02-20T11:30:00Z', createdAt: '2025-02-20T11:25:00Z' },
  { id: 'ord-c06', userId: 'winner-bradley', campaignId: 'camp-c06', ticketCount: 1, totalAmount: 150, status: 'paid' as OrderStatus, paymentMethod: 'eft', paidAt: '2025-03-01T08:15:00Z', createdAt: '2025-03-01T08:10:00Z' },
  // James's expired ticket orders
  { id: 'ord-c07', userId: 'user-james', campaignId: 'camp-c01', ticketCount: 2, totalAmount: 600, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2024-12-15T10:00:00Z', createdAt: '2024-12-15T09:55:00Z' },
  { id: 'ord-c08', userId: 'user-james', campaignId: 'camp-c04', ticketCount: 2, totalAmount: 100, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2024-11-20T14:30:00Z', createdAt: '2024-11-20T14:25:00Z' },
  { id: 'ord-c09', userId: 'user-james', campaignId: 'camp-c04', ticketCount: 1, totalAmount: 50, status: 'paid' as OrderStatus, paymentMethod: 'credit_card', paidAt: '2025-01-05T09:00:00Z', createdAt: '2025-01-05T08:55:00Z' },
  { id: 'ord-c10', userId: 'user-james', campaignId: 'camp-c02', ticketCount: 2, totalAmount: 200, status: 'paid' as OrderStatus, paymentMethod: 'eft', paidAt: '2024-12-10T16:00:00Z', createdAt: '2024-12-10T15:55:00Z' },
];

// ============================================
// 8. PAYMENTS (20 payments)
// ============================================

export const mockPayments: Payment[] = [
  { id: 'pay-001', orderId: 'ord-001', userId: 'user-james', amount: 1000, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250405-001', paidAt: '2025-04-05T10:30:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-001.pdf', createdAt: '2025-04-05T10:28:00Z' },
  { id: 'pay-002', orderId: 'ord-002', userId: 'user-james', amount: 500, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250420-001', paidAt: '2025-04-20T14:15:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-002.pdf', createdAt: '2025-04-20T14:12:00Z' },
  { id: 'pay-003', orderId: 'ord-003', userId: 'user-james', amount: 1000, method: 'eft', status: 'completed' as PaymentStatus, gatewayRef: 'EFT-20250510-001', paidAt: '2025-05-10T09:00:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-003.pdf', createdAt: '2025-05-09T16:00:00Z' },
  { id: 'pay-004', orderId: 'ord-004', userId: 'user-james', amount: 700, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250422-001', paidAt: '2025-04-22T16:45:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-004.pdf', createdAt: '2025-04-22T16:42:00Z' },
  { id: 'pay-005', orderId: 'ord-005', userId: 'user-james', amount: 350, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250508-001', paidAt: '2025-05-08T11:20:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-005.pdf', createdAt: '2025-05-08T11:18:00Z' },
  { id: 'pay-006', orderId: 'ord-006', userId: 'user-james', amount: 200, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250305-001', paidAt: '2025-03-05T08:30:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-006.pdf', createdAt: '2025-03-05T08:28:00Z' },
  { id: 'pay-007', orderId: 'ord-007', userId: 'user-james', amount: 200, method: 'eft', status: 'completed' as PaymentStatus, gatewayRef: 'EFT-20250412-001', paidAt: '2025-04-12T13:00:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-007.pdf', createdAt: '2025-04-11T10:00:00Z' },
  { id: 'pay-008', orderId: 'ord-008', userId: 'user-james', amount: 100, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250520-001', paidAt: '2025-05-20T15:30:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-008.pdf', createdAt: '2025-05-20T15:28:00Z' },
  { id: 'pay-009', orderId: 'ord-009', userId: 'user-james', amount: 400, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250510-002', paidAt: '2025-05-10T10:00:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-009.pdf', createdAt: '2025-05-10T09:55:00Z' },
  { id: 'pay-010', orderId: 'ord-010', userId: 'user-james', amount: 200, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250601-001', paidAt: '2025-06-01T12:15:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-010.pdf', createdAt: '2025-06-01T12:12:00Z' },
  { id: 'pay-011', orderId: 'ord-011', userId: 'user-james', amount: 400, method: 'eft', status: 'completed' as PaymentStatus, gatewayRef: 'EFT-20250425-001', paidAt: '2025-04-25T09:30:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-011.pdf', createdAt: '2025-04-24T14:00:00Z' },
  { id: 'pay-012', orderId: 'ord-012', userId: 'user-james', amount: 200, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250515-001', paidAt: '2025-05-15T14:45:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-012.pdf', createdAt: '2025-05-15T14:42:00Z' },
  { id: 'pay-013', orderId: 'ord-013', userId: 'user-james', amount: 150, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250320-001', paidAt: '2025-03-20T11:00:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-013.pdf', createdAt: '2025-03-20T10:58:00Z' },
  { id: 'pay-014', orderId: 'ord-014', userId: 'user-james', amount: 50, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250428-001', paidAt: '2025-04-28T16:30:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-014.pdf', createdAt: '2025-04-28T16:28:00Z' },
  { id: 'pay-015', orderId: 'ord-015', userId: 'user-james', amount: 600, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250520-002', paidAt: '2025-05-20T08:45:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-015.pdf', createdAt: '2025-05-20T08:42:00Z' },
  { id: 'pay-016', orderId: 'ord-016', userId: 'user-james', amount: 150, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250505-001', paidAt: '2025-05-05T10:15:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-016.pdf', createdAt: '2025-05-05T10:12:00Z' },
  { id: 'pay-017', orderId: 'ord-017', userId: 'user-james', amount: 75, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250602-001', paidAt: '2025-06-02T09:30:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-017.pdf', createdAt: '2025-06-02T09:28:00Z' },
  { id: 'pay-018', orderId: 'ord-018', userId: 'user-james', amount: 150, method: 'credit_card', status: 'completed' as PaymentStatus, gatewayRef: 'GWH-20250605-001', paidAt: '2025-06-05T14:00:00Z', refundedAt: null, invoiceUrl: '/invoices/inv-018.pdf', createdAt: '2025-06-05T13:58:00Z' },
  // Refunded payments
  { id: 'pay-019', orderId: 'ord-019', userId: 'user-james', amount: 500, method: 'credit_card', status: 'refunded' as PaymentStatus, gatewayRef: 'GWH-20250410-001', paidAt: '2025-04-10T08:00:00Z', refundedAt: '2025-04-12T14:00:00Z', invoiceUrl: '/invoices/inv-019.pdf', createdAt: '2025-04-10T07:55:00Z' },
  { id: 'pay-020', orderId: 'ord-020', userId: 'user-james', amount: 350, method: 'credit_card', status: 'refunded' as PaymentStatus, gatewayRef: 'GWH-20250418-001', paidAt: '2025-04-18T12:00:00Z', refundedAt: '2025-04-20T09:30:00Z', invoiceUrl: '/invoices/inv-020.pdf', createdAt: '2025-04-18T11:55:00Z' },
];

// ============================================
// 9. NOTIFICATIONS (15 for demo member)
// ============================================

export const mockNotifications: Notification[] = [
  { id: 'notif-001', userId: 'user-james', type: 'campaign_update', title: 'New Campaign Launched!', message: 'The "Win a Sandton Penthouse Suite" campaign is now live. Get your tickets before they sell out!', channel: 'in_app', status: 'read' as NotificationStatus, deliveryLog: null, sentAt: '2025-04-01T08:00:00Z', readAt: '2025-04-01T10:15:00Z' },
  { id: 'notif-002', userId: 'user-james', type: 'purchase_confirmation', title: 'Purchase Confirmed', message: 'Your purchase of 2 tickets for "Win a Sandton Penthouse Suite" has been confirmed. Total: R1,000.', channel: 'in_app', status: 'read' as NotificationStatus, deliveryLog: null, sentAt: '2025-04-05T10:30:00Z', readAt: '2025-04-05T10:35:00Z' },
  { id: 'notif-003', userId: 'user-james', type: 'purchase_confirmation', title: 'Purchase Confirmed', message: 'Your purchase of 2 tickets for "Drive Home a Mercedes-AMG GT 63 S" has been confirmed. Total: R700.', channel: 'in_app', status: 'read' as NotificationStatus, deliveryLog: null, sentAt: '2025-04-22T16:45:00Z', readAt: '2025-04-22T17:00:00Z' },
  { id: 'notif-004', userId: 'user-james', type: 'campaign_ending', title: 'Campaign Ending Soon!', message: 'The "R500,000 Cash Jackpot" campaign ends in 7 days. Only 75 tickets remaining! Don\'t miss your chance.', channel: 'in_app', status: 'read' as NotificationStatus, deliveryLog: null, sentAt: '2025-06-23T08:00:00Z', readAt: '2025-06-23T09:30:00Z' },
  { id: 'notif-005', userId: 'user-james', type: 'payment_refunded', title: 'Refund Processed', message: 'Your refund of R500 for order #ORD-019 has been processed. The amount will reflect in your account within 3-5 business days.', channel: 'email', status: 'read' as NotificationStatus, deliveryLog: null, sentAt: '2025-04-12T14:00:00Z', readAt: '2025-04-12T18:00:00Z' },
  { id: 'notif-006', userId: 'user-james', type: 'new_campaign', title: '🚗 Porsche 911 Carrera S Raffle is Live!', message: 'A brand new Porsche 911 Carrera S in Guards Red could be yours! R300 per ticket. Draw on 25 August 2025.', channel: 'in_app', status: 'read' as NotificationStatus, deliveryLog: null, sentAt: '2025-05-15T08:00:00Z', readAt: '2025-05-15T12:00:00Z' },
  { id: 'notif-007', userId: 'user-james', type: 'winner_announced', title: '🎉 We Have a Winner!', message: 'Congratulations to Fatima Ebrahim from Durban who won the Mercedes-AMG A45 S in our latest draw! Could you be next?', channel: 'in_app', status: 'read' as NotificationStatus, deliveryLog: null, sentAt: '2025-05-10T19:00:00Z', readAt: '2025-05-11T08:00:00Z' },
  { id: 'notif-008', userId: 'user-james', type: 'ticket_reminder', title: 'Don\'t Forget Your Active Tickets', message: 'You currently have 31 active tickets across 11 campaigns. Check your dashboard to see where you stand!', channel: 'push', status: 'read' as NotificationStatus, deliveryLog: null, sentAt: '2025-06-10T09:00:00Z', readAt: '2025-06-10T11:00:00Z' },
  { id: 'notif-009', userId: 'user-james', type: 'campaign_update', title: 'Clifton Beach Villa Campaign - 47% Sold', message: 'The Clifton Beach Villa raffle is almost halfway sold. With a R12M prize, this is our biggest property raffle ever!', channel: 'in_app', status: 'unread' as NotificationStatus, deliveryLog: null, sentAt: '2025-06-12T08:00:00Z', readAt: null },
  { id: 'notif-010', userId: 'user-james', type: 'special_offer', title: 'Exclusive: Buy 3 Tickets, Get 1 Free!', message: 'This weekend only — buy 3 tickets for any campaign and get a 4th ticket absolutely free. Use code: JKBFREE4 at checkout.', channel: 'email', status: 'unread' as NotificationStatus, deliveryLog: null, sentAt: '2025-06-12T10:00:00Z', readAt: null },
  { id: 'notif-011', userId: 'user-james', type: 'purchase_confirmation', title: 'Purchase Confirmed', message: 'Your purchase of 3 tickets for "MacBook Pro 16" M3 Max Bundle" has been confirmed. Total: R150.', channel: 'in_app', status: 'unread' as NotificationStatus, deliveryLog: null, sentAt: '2025-06-05T14:00:00Z', readAt: null },
  { id: 'notif-012', userId: 'user-james', type: 'draw_reminder', title: 'Draw Reminder: Samsung 85" TV', message: 'The draw for the Samsung 85" Neo QLED 8K TV is happening on 5 July at Baywest Mall, Gqeberha. You hold 4 tickets!', channel: 'sms', status: 'unread' as NotificationStatus, deliveryLog: null, sentAt: '2025-06-28T12:00:00Z', readAt: null },
  { id: 'notif-013', userId: 'user-james', type: 'system', title: 'JK Raffle App Update Available', message: 'We\'ve improved ticket management and added new payment methods. Update your app to get the latest features.', channel: 'push', status: 'unread' as NotificationStatus, deliveryLog: null, sentAt: '2025-06-11T16:00:00Z', readAt: null },
  { id: 'notif-014', userId: 'user-james', type: 'community', title: 'Join Our WhatsApp Community', message: 'Get instant draw results, exclusive deals, and winner stories directly on WhatsApp. Tap to join the JK Raffle community!', channel: 'whatsapp', status: 'unread' as NotificationStatus, deliveryLog: null, sentAt: '2025-06-09T14:00:00Z', readAt: null },
  { id: 'notif-015', userId: 'user-james', type: 'account', title: 'Your JK Raffle Account Anniversary', message: 'Happy 9 months with JK Raffle, James! You\'ve purchased 50+ tickets and been part of 15 campaigns. Thank you for your loyalty! 🎉', channel: 'in_app', status: 'unread' as NotificationStatus, deliveryLog: null, sentAt: '2025-06-12T00:00:00Z', readAt: null },
];

// ============================================
// 10. ACTIVITY LOGS (10 for demo user)
// ============================================

export const mockActivityLogs: ActivityLog[] = [
  { id: 'alog-001', userId: 'user-james', action: 'user.login', entity: 'user', entityId: 'user-james', details: { ip: '196.21.45.112', device: 'Chrome on Windows', location: 'Sandton, Gauteng' }, createdAt: '2025-06-12T11:20:00Z' },
  { id: 'alog-002', userId: 'user-james', action: 'order.create', entity: 'order', entityId: 'ord-018', details: { campaignId: 'camp-009', ticketCount: 3, totalAmount: 150, paymentMethod: 'credit_card' }, createdAt: '2025-06-05T13:58:00Z' },
  { id: 'alog-003', userId: 'user-james', action: 'order.create', entity: 'order', entityId: 'ord-017', details: { campaignId: 'camp-012', ticketCount: 1, totalAmount: 75, paymentMethod: 'credit_card' }, createdAt: '2025-06-02T09:28:00Z' },
  { id: 'alog-004', userId: 'user-james', action: 'order.create', entity: 'order', entityId: 'ord-015', details: { campaignId: 'camp-005', ticketCount: 2, totalAmount: 600, paymentMethod: 'credit_card' }, createdAt: '2025-05-20T08:42:00Z' },
  { id: 'alog-005', userId: 'user-james', action: 'order.create', entity: 'order', entityId: 'ord-012', details: { campaignId: 'camp-006', ticketCount: 1, totalAmount: 200, paymentMethod: 'credit_card' }, createdAt: '2025-05-15T14:42:00Z' },
  { id: 'alog-006', userId: 'user-james', action: 'order.create', entity: 'order', entityId: 'ord-010', details: { campaignId: 'camp-004', ticketCount: 1, totalAmount: 200, paymentMethod: 'credit_card' }, createdAt: '2025-06-01T12:12:00Z' },
  { id: 'alog-007', userId: 'user-james', action: 'order.create', entity: 'order', entityId: 'ord-009', details: { campaignId: 'camp-004', ticketCount: 2, totalAmount: 400, paymentMethod: 'credit_card' }, createdAt: '2025-05-10T09:55:00Z' },
  { id: 'alog-008', userId: 'user-james', action: 'order.refund', entity: 'order', entityId: 'ord-019', details: { campaignId: 'camp-001', refundAmount: 500, reason: 'Changed mind' }, createdAt: '2025-04-12T14:00:00Z' },
  { id: 'alog-009', userId: 'user-james', action: 'ticket.view', entity: 'ticket', entityId: 'tkt-001', details: { campaignTitle: 'Win a Sandton Penthouse Suite', reference: 'JKR-SPH-012' }, createdAt: '2025-06-11T15:30:00Z' },
  { id: 'alog-010', userId: 'user-james', action: 'profile.update', entity: 'user', entityId: 'user-james', details: { field: 'phone', oldValue: '+27 85 555 0000', newValue: '+27 85 555 4004' }, createdAt: '2025-05-28T10:00:00Z' },
];

// ============================================
// 11. SUPPORT TICKETS (5)
// ============================================

export const mockSupportTickets: SupportTicket[] = [
  {
    id: 'stkt-001',
    userId: 'user-james',
    subject: 'Refund not received for Order #ORD-019',
    description: 'I requested a refund on 10 April for order #ORD-019 (R500 for the Sandton Penthouse campaign). The notification says it was processed on 12 April, but the amount has not reflected in my credit card account yet. It\'s been over a week.',
    status: 'resolved' as SupportTicketStatus,
    priority: 'medium' as SupportTicketPriority,
    category: 'payments',
    assignedTo: 'user-lisa',
    resolution: 'Refund confirmed with the payment gateway. The bank processing time was longer than usual due to a public holiday. The R500 refund reflected in the customer\'s account on 21 April.',
    createdAt: '2025-04-20T09:00:00Z',
    updatedAt: '2025-04-21T14:30:00Z',
    resolvedAt: '2025-04-21T14:30:00Z',
  },
  {
    id: 'stkt-002',
    userId: 'user-james',
    subject: 'Unable to add more tickets to cart',
    description: 'When I try to add tickets for the Clifton Beach Villa campaign to my cart, I get an error message saying "Maximum ticket limit reached for this campaign." But I\'ve only purchased 1 ticket so far. Please assist.',
    status: 'resolved' as SupportTicketStatus,
    priority: 'high' as SupportTicketPriority,
    category: 'technical',
    assignedTo: 'user-lisa',
    resolution: 'There was a temporary session cache issue causing the system to count tickets from a previous abandoned cart. The cache was cleared and the user was able to purchase additional tickets successfully.',
    createdAt: '2025-06-01T11:00:00Z',
    updatedAt: '2025-06-01T14:00:00Z',
    resolvedAt: '2025-06-01T14:00:00Z',
  },
  {
    id: 'stkt-003',
    userId: 'user-james',
    subject: 'Question about draw verification process',
    description: 'Hi, I\'m curious about how the draw verification works. Is it done by an independent auditor? Can I attend the draw in person? I see the Samsung TV draw is at Baywest Mall — can anyone watch?',
    status: 'resolved' as SupportTicketStatus,
    priority: 'low' as SupportTicketPriority,
    category: 'general',
    assignedTo: 'user-lisa',
    resolution: 'All draws are verified by our internal auditor (Michael Mabuza) and conducted in public spaces where all ticket holders are welcome to attend. Draws are also live-streamed on our social media channels.',
    createdAt: '2025-06-05T10:00:00Z',
    updatedAt: '2025-06-05T12:00:00Z',
    resolvedAt: '2025-06-05T12:00:00Z',
  },
  {
    id: 'stkt-004',
    userId: 'user-james',
    subject: 'EFT payment pending for over 24 hours',
    description: 'I made an EFT payment of R400 for the Maldives campaign (order #ORD-011) yesterday. The payment shows as pending in my account but the money has already left my bank account. Reference: EFT-20250425-001.',
    status: 'in_progress' as SupportTicketStatus,
    priority: 'high' as SupportTicketPriority,
    category: 'payments',
    assignedTo: 'user-lisa',
    resolution: null,
    createdAt: '2025-06-11T08:30:00Z',
    updatedAt: '2025-06-12T09:00:00Z',
    resolvedAt: null,
  },
  {
    id: 'stkt-005',
    userId: 'user-james',
    subject: 'Request for ticket purchase history report',
    description: 'Hi, I need a detailed report of all my ticket purchases for the 2024/2025 tax year. I need this for my personal financial records. Can you generate and email this to me?',
    status: 'open' as SupportTicketStatus,
    priority: 'low' as SupportTicketPriority,
    category: 'account',
    assignedTo: null,
    resolution: null,
    createdAt: '2025-06-12T08:00:00Z',
    updatedAt: '2025-06-12T08:00:00Z',
    resolvedAt: null,
  },
];

// ============================================
// 12. EVENTS (8)
// ============================================

export const mockEvents: Event[] = [
  {
    id: 'evt-001',
    title: 'Samsung 85" TV Live Draw',
    description: 'Join us for the live draw of the Samsung 85" Neo QLED 8K TV raffle at Baywest Mall. Free refreshments for ticket holders!',
    type: 'draw' as EventTypes,
    date: '2025-07-05T17:00:00Z',
    endDate: '2025-07-05T19:00:00Z',
    location: 'Baywest Mall, Centre Court, Gqeberha',
    campaignId: 'camp-008',
    branchId: 'branch-pe-c',
    status: 'upcoming' as EventStatus,
    createdAt: '2025-06-01T08:00:00Z',
  },
  {
    id: 'evt-002',
    title: 'R250,000 Cash Draw — Polokwane',
    description: 'The R250,000 Cash Prize draw happening live at Mall of the North. Come and see if lady luck is on your side!',
    type: 'draw' as EventTypes,
    date: '2025-07-10T17:30:00Z',
    endDate: '2025-07-10T19:00:00Z',
    location: 'Mall of the North, Polokwane',
    campaignId: 'camp-012',
    branchId: 'branch-pkw-c',
    status: 'upcoming' as EventStatus,
    createdAt: '2025-06-05T08:00:00Z',
  },
  {
    id: 'evt-003',
    title: 'JK Raffle Sandton Branch Open Day',
    description: 'Visit our flagship Sandton branch for an open day! Meet the team, learn about upcoming campaigns, and enjoy exclusive on-the-day discounts. Free boerewors rolls and refreshments!',
    type: 'branch_event' as EventTypes,
    date: '2025-07-19T10:00:00Z',
    endDate: '2025-07-19T16:00:00Z',
    location: 'JK Raffle Sandton Branch, Sandton City Mall',
    campaignId: null,
    branchId: 'branch-jhb-n',
    status: 'upcoming' as EventStatus,
    createdAt: '2025-06-10T08:00:00Z',
  },
  {
    id: 'evt-004',
    title: 'R500K Cash Jackpot Live Draw',
    description: 'The biggest cash draw of the quarter! R500,000 up for grabs at Gateway Theatre of Shopping. Live streaming available on our Facebook and YouTube channels.',
    type: 'draw' as EventTypes,
    date: '2025-06-30T17:00:00Z',
    endDate: '2025-06-30T19:00:00Z',
    location: 'Gateway Theatre of Shopping, Umhlanga',
    campaignId: 'camp-003',
    branchId: 'branch-dbn-c',
    status: 'upcoming' as EventStatus,
    createdAt: '2025-05-15T08:00:00Z',
  },
  {
    id: 'evt-005',
    title: 'JK Raffle Community Giveback — Soweto',
    description: 'JK Raffle gives back to the community! Join us for a fun-filled day with food, music, and free raffle entries for Soweto residents. Part of our corporate social responsibility programme.',
    type: 'community' as EventTypes,
    date: '2025-08-16T09:00:00Z',
    endDate: '2025-08-16T17:00:00Z',
    location: 'Dobsonville Community Hall, Soweto',
    campaignId: null,
    branchId: 'branch-jhb-s',
    status: 'upcoming' as EventStatus,
    createdAt: '2025-06-08T08:00:00Z',
  },
  {
    id: 'evt-006',
    title: 'Mercedes-AMG GT 63 S Draw — V&A Waterfront',
    description: 'The draw for the stunning Mercedes-AMG GT 63 S at the iconic V&A Waterfront. A spectacular evening event with the Mercedes on display before the draw.',
    type: 'draw' as EventTypes,
    date: '2025-07-28T19:00:00Z',
    endDate: '2025-07-28T21:00:00Z',
    location: 'V&A Waterfront Amphitheatre, Cape Town',
    campaignId: 'camp-002',
    branchId: 'branch-cpt-c',
    status: 'upcoming' as EventStatus,
    createdAt: '2025-06-01T08:00:00Z',
  },
  {
    id: 'evt-007',
    title: 'JK Raffle Winter Promo Launch',
    description: 'Launch of our Winter Wonder Draw season with exciting new campaigns, bonus ticket offers, and a chance to win double prizes. Running across all branches nationwide!',
    type: 'promotional' as EventTypes,
    date: '2025-06-15T00:00:00Z',
    endDate: '2025-08-31T23:59:59Z',
    location: 'All JK Raffle Branches Nationwide',
    campaignId: null,
    branchId: null,
    status: 'ongoing' as EventStatus,
    createdAt: '2025-06-10T08:00:00Z',
  },
  {
    id: 'evt-008',
    title: 'Mercedes-AMG A45 S Draw Event (Completed)',
    description: 'The Mercedes-AMG A45 S was won by Fatima Ebrahim from Durban at this exciting live draw event at Galleria Mall.',
    type: 'draw' as EventTypes,
    date: '2025-05-10T18:00:00Z',
    endDate: '2025-05-10T20:00:00Z',
    location: 'Galleria Mall, Amanzimtot',
    campaignId: 'camp-c05',
    branchId: 'branch-dbn-s',
    status: 'completed' as EventStatus,
    createdAt: '2025-04-15T08:00:00Z',
  },
];

// ============================================
// 13. FAQ (10+ items for public website)
// ============================================

export interface FAQItem {
  id: string;
  question: string;
  answer: string;
  category: string;
  order: number;
}

export const mockFAQ: FAQItem[] = [
  {
    id: 'faq-001',
    question: 'How do JK Raffle competitions work?',
    answer: 'JK Raffle runs licensed raffle competitions where you purchase numbered tickets for a chance to win luxury prizes. Each campaign has a fixed number of tickets and a scheduled draw date. When all tickets are sold (or the draw date arrives), a random draw is conducted under independent audit supervision. The ticket holder whose number is drawn wins the prize!',
    category: 'general',
    order: 1,
  },
  {
    id: 'faq-002',
    question: 'Are JK Raffle competitions legal in South Africa?',
    answer: 'Yes, absolutely. JK Raffle operates in full compliance with the South African National Gambling Board regulations and the National Gambling Act of 2004 (as amended). All our draws are conducted transparently with independent auditing, and we are registered as a licensed raffle operator.',
    category: 'legal',
    order: 2,
  },
  {
    id: 'faq-003',
    question: 'How much do tickets cost?',
    answer: 'Ticket prices vary depending on the prize value and campaign. Our tickets range from R50 to R500 each. Higher-value prizes like luxury homes and supercars typically have tickets priced at R300-R500, while electronics and cash prizes may have tickets starting from R50-R100.',
    category: 'tickets',
    order: 3,
  },
  {
    id: 'faq-004',
    question: 'How many tickets can I buy per campaign?',
    answer: 'There is no strict limit on the number of tickets you can purchase per campaign, subject to availability. However, each individual may purchase a maximum of 10% of the total available tickets for any single campaign. For example, if a campaign has 200 tickets, you can buy up to 20 tickets.',
    category: 'tickets',
    order: 4,
  },
  {
    id: 'faq-005',
    question: 'What payment methods do you accept?',
    answer: 'We accept multiple payment methods for your convenience: Credit/Debit Cards (Visa, Mastercard, American Express), EFT (Electronic Funds Transfer), SnapScan, Zapper, and ABSA CashSend. All online payments are secured with 256-bit SSL encryption.',
    category: 'payments',
    order: 5,
  },
  {
    id: 'faq-006',
    question: 'How are winners selected?',
    answer: 'Winners are selected through a verified random draw process. For physical draws, we use a certified random number generator displayed on screen at a public venue. All draws are supervised by our internal auditor and conducted in public spaces where ticket holders are welcome to attend. Draws are also live-streamed on our social media channels for full transparency.',
    category: 'draws',
    order: 6,
  },
  {
    id: 'faq-007',
    question: 'How do I know if I\'ve won?',
    answer: 'Winners are notified immediately after the draw via email, SMS, WhatsApp, and in-app notification. We also announce winners on our website, Facebook, Instagram, and YouTube channels. If your ticket is drawn, our winner verification team will contact you within 24 hours to begin the prize claim process.',
    category: 'winners',
    order: 7,
  },
  {
    id: 'faq-008',
    question: 'How long does it take to receive my prize?',
    answer: 'Cash prizes are deposited into your verified bank account within 48 hours of winner verification. For physical prizes (vehicles, electronics), delivery or collection is arranged within 7-14 business days. Property prizes involve a transfer process that typically takes 4-8 weeks, during which our legal team assists with all conveyancing.',
    category: 'winners',
    order: 8,
  },
  {
    id: 'faq-009',
    question: 'Do I have to pay tax on my winnings?',
    answer: 'In South Africa, winnings from licensed raffle competitions are generally not subject to income tax for the winner, as per SARS guidelines. However, we recommend consulting with a tax professional for personalised advice, especially for high-value prizes like property.',
    category: 'legal',
    order: 9,
  },
  {
    id: 'faq-010',
    question: 'Can I get a refund on my ticket purchase?',
    answer: 'Ticket purchases are generally considered final as they represent entry into a competition. However, we understand that circumstances change. Refund requests can be submitted within 24 hours of purchase, subject to a R25 administration fee. Refunds are not available once a campaign has entered its final week before the draw date. Contact our support team for assistance.',
    category: 'payments',
    order: 10,
  },
  {
    id: 'faq-011',
    question: 'Can I transfer my ticket to someone else?',
    answer: 'No, tickets are non-transferable. Each ticket is registered to the purchasing member\'s account and cannot be sold, gifted, or transferred to another person. This policy ensures the integrity of our draws and compliance with gambling regulations.',
    category: 'tickets',
    order: 11,
  },
  {
    id: 'faq-012',
    question: 'What happens if a campaign doesn\'t sell all tickets?',
    answer: 'The draw will still take place on the scheduled draw date even if not all tickets are sold. The odds of winning actually improve for ticket holders when fewer tickets are sold! However, JK Raffle reserves the right to extend the campaign deadline by a maximum of 30 days if fewer than 50% of tickets are sold, to ensure a fair prize pool.',
    category: 'general',
    order: 12,
  },
  {
    id: 'faq-013',
    question: 'How do I create an account and start buying tickets?',
    answer: 'Creating an account is free and takes less than 2 minutes. Click "Sign Up" on our website, provide your name, email, phone number, and South African ID number (for winner verification). Once verified, you can browse active campaigns, add tickets to your cart, and pay securely online. You can also visit any of our 20 branches nationwide to purchase in person.',
    category: 'general',
    order: 13,
  },
  {
    id: 'faq-014',
    question: 'Is my personal information safe with JK Raffle?',
    answer: 'Absolutely. We take data protection very seriously and comply with the Protection of Personal Information Act (POPIA). Your personal information is encrypted and stored securely. We never sell or share your data with third parties for marketing purposes. You can review and manage your data preferences in your account settings at any time.',
    category: 'legal',
    order: 14,
  },
];

// ============================================
// 14. DASHBOARD STATISTICS
// ============================================

export const mockDashboardStats: DashboardStats = {
  totalRevenue: 12850000,
  totalTicketsSold: 4823,
  totalMembers: 3769,
  activeCampaigns: 12,
  totalOrders: 4150,
  pendingPayments: 23,
  totalWinners: 156,
  monthlyGrowth: 12.5,
  revenueByMonth: [
    { month: 'Jul 2024', revenue: 680000, tickets: 312 },
    { month: 'Aug 2024', revenue: 720000, tickets: 345 },
    { month: 'Sep 2024', revenue: 810000, tickets: 380 },
    { month: 'Oct 2024', revenue: 950000, tickets: 420 },
    { month: 'Nov 2024', revenue: 880000, tickets: 395 },
    { month: 'Dec 2024', revenue: 1120000, tickets: 478 },
    { month: 'Jan 2025', revenue: 1050000, tickets: 450 },
    { month: 'Feb 2025', revenue: 980000, tickets: 425 },
    { month: 'Mar 2025', revenue: 1150000, tickets: 488 },
    { month: 'Apr 2025', revenue: 1340000, tickets: 540 },
    { month: 'May 2025', revenue: 1480000, tickets: 590 },
    { month: 'Jun 2025', revenue: 690000, tickets: 240 }, // Partial month
  ],
  ticketsByBranch: [
    { branch: 'Cape Town Central', tickets: 680, revenue: 1720000 },
    { branch: 'Johannesburg North', tickets: 590, revenue: 1450000 },
    { branch: 'Durban Central', tickets: 475, revenue: 1180000 },
    { branch: 'Pretoria Central', tickets: 430, revenue: 1050000 },
    { branch: 'Johannesburg South', tickets: 360, revenue: 890000 },
    { branch: 'Cape Town Southern', tickets: 320, revenue: 780000 },
    { branch: 'Port Elizabeth', tickets: 265, revenue: 640000 },
    { branch: 'Johannesburg East', tickets: 250, revenue: 620000 },
    { branch: 'Pretoria East', tickets: 235, revenue: 580000 },
    { branch: 'Durban South', tickets: 210, revenue: 510000 },
    { branch: 'Bloemfontein', tickets: 158, revenue: 380000 },
    { branch: 'Nelspruit', tickets: 175, revenue: 420000 },
    { branch: 'Pietermaritzburg', tickets: 165, revenue: 390000 },
    { branch: 'Stellenbosch', tickets: 152, revenue: 360000 },
    { branch: 'Rustenburg', tickets: 122, revenue: 290000 },
    { branch: 'Vereeniging', tickets: 105, revenue: 250000 },
    { branch: 'George', tickets: 100, revenue: 240000 },
    { branch: 'East London', tickets: 115, revenue: 280000 },
    { branch: 'Polokwane', tickets: 130, revenue: 310000 },
    { branch: 'Kimberley', tickets: 82, revenue: 190000 },
  ],
  recentActivity: mockActivityLogs.slice(0, 5),
  topCampaigns: mockCampaigns
    .filter(c => c.status === 'open')
    .sort((a, b) => b.soldTickets - a.soldTickets)
    .slice(0, 5),
};

// ============================================
// 15. WINNER DATA (for completed campaigns)
// ============================================

export interface WinnerInfo {
  id: string;
  firstName: string;
  lastName: string;
  city: string;
  province: string;
  campaignTitle: string;
  prizeName: string;
  prizeValue: number;
  wonAt: string;
  ticketReference: string;
  quote?: string;
}

export const mockRecentWinners: WinnerInfo[] = [
  {
    id: 'winner-bradley',
    firstName: 'Bradley',
    lastName: 'van Wyk',
    city: 'Gqeberha',
    province: 'Eastern Cape',
    campaignTitle: 'R750,000 Cash Grand Prize',
    prizeName: 'R750,000 Cash',
    prizeValue: 750000,
    wonAt: '2025-05-25T17:00:00Z',
    ticketReference: 'JKR-75K-445',
    quote: 'I still can\'t believe it! I was buying tickets for the first time and won R750,000. JK Raffle changed my life — I\'m paying off my bond and starting a small business!',
  },
  {
    id: 'winner-fatima',
    firstName: 'Fatima',
    lastName: 'Ebrahim',
    city: 'Durban',
    province: 'KwaZulu-Natal',
    campaignTitle: 'Mercedes-AMG A45 S Raffle',
    prizeName: 'Mercedes-AMG A45 S',
    prizeValue: 1200000,
    wonAt: '2025-05-10T18:00:00Z',
    ticketReference: 'JKR-A45-087',
    quote: 'I\'ve been entering JK Raffle competitions for over a year. When they called my name at the Galleria Mall draw, I burst into tears! My dream car is now sitting in my driveway.',
  },
  {
    id: 'winner-thandiwe',
    firstName: 'Thandiwe',
    lastName: 'Mthembu',
    city: 'Pretoria',
    province: 'Gauteng',
    campaignTitle: 'Zanzibar Beach Holiday Raffle',
    prizeName: '10-Night Zanzibar Holiday for Two',
    prizeValue: 120000,
    wonAt: '2025-04-20T18:00:00Z',
    ticketReference: 'JKR-ZNZ-234',
    quote: 'My husband and I had never been overseas before. The Zanzibar trip was absolutely magical — the resort, the food, the sunset dhow cruise. Thank you JK Raffle for an unforgettable experience!',
  },
  {
    id: 'winner-nompumelelo',
    firstName: 'Nompumelelo',
    lastName: 'Dlamini',
    city: 'Umhlanga',
    province: 'KwaZulu-Natal',
    campaignTitle: 'Umhlanga Coastal Apartment Raffle',
    prizeName: '2-Bedroom Apartment in Umhlanga Ridge',
    prizeValue: 3200000,
    wonAt: '2025-03-15T18:00:00Z',
    ticketReference: 'JKR-UMH-187',
    quote: 'Owning property in Umhlanga was a dream I never thought would come true. JK Raffle made it happen! The apartment is beautiful and I can hear the ocean from my balcony.',
  },
  {
    id: 'winner-aarav',
    firstName: 'Aarav',
    lastName: 'Naidoo',
    city: 'Cape Town',
    province: 'Western Cape',
    campaignTitle: 'Sony Alpha 1 Camera Bundle',
    prizeName: 'Sony Alpha 1 + 2 Lenses',
    prizeValue: 175000,
    wonAt: '2025-02-28T17:00:00Z',
    ticketReference: 'JKR-CAM-098',
    quote: 'As a wildlife photographer, the Sony Alpha 1 is a game-changer. I\'ve already used it on two safari trips and the image quality is breathtaking. Best R100 I ever spent!',
  },
  {
    id: 'winner-sipho',
    firstName: 'Sipho',
    lastName: 'Moloi',
    city: 'Johannesburg',
    province: 'Gauteng',
    campaignTitle: 'R200,000 Cash Bonanza',
    prizeName: 'R200,000 Cash',
    prizeValue: 200000,
    wonAt: '2025-01-31T17:00:00Z',
    ticketReference: 'JKR-CS2-312',
    quote: 'R200,000 came at the perfect time — I used it to pay for my daughter\'s university tuition fees for the year. JK Raffle is legit and I recommend it to everyone!',
  },
];

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Returns all open/active campaigns sorted by draw date (soonest first)
 */
export function getActiveCampaigns(): Campaign[] {
  return mockCampaigns
    .filter(c => c.status === 'open')
    .sort((a, b) => new Date(a.drawDate).getTime() - new Date(b.drawDate).getTime());
}

/**
 * Returns 4 featured campaigns for homepage display
 */
export function getFeaturedCampaigns(): Campaign[] {
  const openFeatured = mockCampaigns
    .filter(c => c.status === 'open' && c.product.featured)
    .sort((a, b) => b.progress - a.progress)
    .slice(0, 4);

  // If we don't have 4 featured, fill with top open campaigns
  if (openFeatured.length < 4) {
    const remaining = mockCampaigns
      .filter(c => c.status === 'open' && !openFeatured.includes(c))
      .sort((a, b) => b.progress - a.progress);
    openFeatured.push(...remaining.slice(0, 4 - openFeatured.length));
  }

  return openFeatured.slice(0, 4);
}

/**
 * Returns completed campaigns with winner information
 */
export function getRecentWinners(): (Campaign & { winnerInfo?: WinnerInfo })[] {
  return mockCampaigns
    .filter(c => c.status === 'completed')
    .map(campaign => {
      const winner = mockRecentWinners.find(w => w.id === campaign.winnerId);
      return { ...campaign, winnerInfo: winner };
    })
    .sort((a, b) => new Date(b.drawnAt!).getTime() - new Date(a.drawnAt!).getTime());
}

/**
 * Returns computed stats for a specific branch
 */
export function getBranchStats(branchId: string) {
  const branch = mockBranches.find(b => b.id === branchId);
  if (!branch) return null;

  const branchCampaigns = mockCampaigns.filter(c => c.branchId === branchId);
  const activeCampaigns = branchCampaigns.filter(c => c.status === 'open');
  const completedCampaigns = branchCampaigns.filter(c => c.status === 'completed');

  const totalTicketsSold = branchCampaigns.reduce((sum, c) => sum + c.soldTickets, 0);
  const totalRevenue = branchCampaigns.reduce((sum, c) => sum + (c.soldTickets * c.ticketPrice), 0);

  return {
    branch,
    activeCampaignCount: activeCampaigns.length,
    completedCampaignCount: completedCampaigns.length,
    totalTicketsSold,
    totalRevenue,
    averageProgress: activeCampaigns.length > 0
      ? Math.round(activeCampaigns.reduce((sum, c) => sum + (c.progress || 0), 0) / activeCampaigns.length)
      : 0,
    upcomingDraws: activeCampaigns
      .sort((a, b) => new Date(a.drawDate).getTime() - new Date(b.drawDate).getTime())
      .map(c => ({
        campaignTitle: c.title,
        drawDate: c.drawDate,
        progress: c.progress || 0,
        ticketsRemaining: c.maxTickets - c.soldTickets,
      })),
  };
}